local h = require("tests.helper")
local R = h.loadLib()
local Accordion, Create = R.Accordion, R.Create

local function parentWithLayout()
  local p = Create("Frame", {})
  Create("UIListLayout", { Parent = p })
  return p
end

h.describe("accordion", function()
  h.it("container clips and is auto-size None (tween-controlled)", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "Advanced", Icon = "settings-2" })
    h.expect(acc.Container.ClipsDescendants).toBe(true)
    h.expect(acc.Container.AutomaticSize.Name).toBe("None")
    h.expect(acc.Container.Parent).toBe(p)
  end)
  h.it("content uses UIListLayout + AutomaticSize.Y", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    h.expect(acc.Content.AutomaticSize.Name).toBe("Y")
    h.expect(acc.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
  end)
  h.it("renders as a bordered card with a divider that shows only when expanded", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv", Expanded = false })
    h.expect(acc.Container:FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local divider = acc.Container:FindFirstChild("Divider")
    h.expect(divider ~= nil).toBeTruthy()
    h.expect(divider.Visible).toBe(false)
    acc:Expand()
    h.expect(divider.Visible).toBe(true)
  end)
  h.it("does not recolor the container on header hover", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X" })
    local base = acc.Container.BackgroundColor3
    acc.Header.MouseEnter:Fire()
    h.expect(acc.Container.BackgroundColor3).toBe(base)
  end)
  h.it("MountRow assigns incrementing LayoutOrder under Content", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    local a = Create("Frame", {}); local b = Create("Frame", {})
    local o1 = acc.MountRow(a); local o2 = acc.MountRow(b)
    h.expect(a.Parent).toBe(acc.Content)
    h.expect(o2 > o1).toBeTruthy()
  end)
  -- Motion (Task 2): caret rotation + spring height + slide reveal
  h.it("collapsed by default: header height, caret unrotated, content hidden", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a.Container.Size.Y.Offset).toBe(34)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Content.Visible).toBe(false)
  end)
  h.it("Expand rotates caret to 90, shows content, hands height to AutomaticSize.Y", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    a:Expand()
    h.expect(a:IsExpanded()).toBe(true)
    h.expect(a.Content.Visible).toBe(true)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(90)
    h.expect(a.Container.AutomaticSize.Name).toBe("Y")   -- engine fits content (no script re-measure)
  end)
  h.it("Collapse rotates caret back to 0, hides content, returns to header height", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec", Expanded = true })
    a:Collapse()
    h.expect(a:IsExpanded()).toBe(false)
    h.expect(a.Content.Visible).toBe(false)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Container.Size.Y.Offset).toBe(34)
  end)
  h.it("Toggle flips expansion and returns the new state", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a:Toggle()).toBe(true)
    h.expect(a:Toggle()).toBe(false)
  end)
  -- Height is engine-driven (AutomaticSize.Y) when expanded, so tall/dynamic content (reactive
  -- paragraphs) keeps fitting WITHOUT any post-construction script write -- which is what fails on
  -- executors that deny the GUI capability to Heartbeat/signal handlers (content was clipped there).
  h.it("expanded => AutomaticSize.Y (engine-driven), collapsed => fixed header height", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X", Expanded = true })
    h.expect(acc.Container.AutomaticSize.Name).toBe("Y")
    acc:Collapse()
    h.expect(acc.Container.AutomaticSize.Name).toBe("None")
    h.expect(acc.Container.Size.Y.Offset).toBe(34)
    acc:Expand()
    h.expect(acc.Container.AutomaticSize.Name).toBe("Y")
  end)
  h.it("adding content does not depend on a Heartbeat re-measure (no scheduler write)", function()
    -- Construction + AddX must not throw or require a stepHeartbeat to size correctly; the engine
    -- handles it. (A no-op stepHeartbeat must leave an expanded accordion AutomaticSize.Y.)
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X", Expanded = true })
    acc:AddParagraph("a\nb\nc")
    acc:AddButton({ Text = "Go" })
    h.mock.stepHeartbeat(0)
    h.expect(acc.Container.AutomaticSize.Name).toBe("Y")
  end)
end)


-- Visual polish (plan 1.2 / 1.4 / 1.10): label font role, caret rest/active tint, content inset.
h.describe("accordion polish", function()
  local Enum, mock, theme = h.roblox.Enum, h.mock, R.Theme

  h.it("Title uses the theme label role (Medium 14)", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv" })
    local title = acc.Header:FindFirstChild("Title")
    h.expect(title.Font).toBe(Enum.Font.BuilderSans)
    h.expect(title.TextSize).toBe(theme.Font.label.Size)
    h.expect(title.FontFace.Weight).toBe(theme.Font.label.Weight)
  end)
  h.it("caret rests muted collapsed, lifts to foreground expanded (tween over Motion.fast); lead icon stays accent", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv", Icon = "settings-2" })
    local caret, lead = acc.Header:FindFirstChild("Caret"), acc.Header:FindFirstChild("Icon")
    h.expect(caret.ImageColor3).toBe(theme.Colors.mutedForeground)
    h.expect(lead.ImageColor3).toBe(theme.Colors.primary)
    mock.resetTweens()
    acc:Expand()
    h.expect(caret.ImageColor3).toBe(theme.Colors.foreground)
    h.expect(lead.ImageColor3).toBe(theme.Colors.primary)
    local tint
    for _, tw in ipairs(mock.tweensFor(caret)) do if tw.Goal.ImageColor3 then tint = tw end end
    h.expect(tint ~= nil).toBeTruthy()
    h.expect(tint.Goal.ImageColor3).toBe(theme.Colors.foreground)
    h.expect(tint.Info.Time).toBe(theme.Motion.fast)
    acc:Collapse()
    h.expect(caret.ImageColor3).toBe(theme.Colors.mutedForeground)
  end)
  h.it("Expanded = true at build paints the caret foreground without a tween", function()
    mock.resetTweens()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv", Expanded = true })
    local caret = acc.Header:FindFirstChild("Caret")
    h.expect(caret.ImageColor3).toBe(theme.Colors.foreground)
    h.expect(#mock.tweensFor(caret)).toBe(0)
  end)
  h.it("Content inset matches the header title: inputX left/right, inputY bottom", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv" })
    local pad = acc.Content:FindFirstChildOfClass("UIPadding")
    h.expect(pad.PaddingLeft.Offset).toBe(theme.Spacing.inputX)
    h.expect(pad.PaddingRight.Offset).toBe(theme.Spacing.inputX)
    h.expect(pad.PaddingBottom.Offset).toBe(theme.Spacing.inputY)
    h.expect(pad.PaddingTop.Offset).toBe(0)
  end)
  h.it("themer closure re-derives the caret role by state (muted collapsed, foreground expanded)", function()
    local custom, themer = R.Theme.new(), R.Themer.new()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv", Icon = "settings-2",
      Theme = custom, AccentThemer = themer })
    local caret, lead = acc.Header:FindFirstChild("Caret"), acc.Header:FindFirstChild("Icon")
    R.Theme.applyMode(custom, "light")
    themer.reskin("mode")
    h.expect(caret.ImageColor3).toBe(R.Theme.PALETTES.light.mutedForeground)
    h.expect(lead.ImageColor3).toBe(custom.Colors.primary)
    acc:Expand()
    themer.reskin("mode")
    h.expect(caret.ImageColor3).toBe(R.Theme.PALETTES.light.foreground)
    h.expect(caret.Rotation).toBe(90)
  end)
  h.it("reduced motion: Toggle lands caret colour + rotation and the height with zero tweens", function()
    h.withReducedMotion(R, function()
      local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv" })
      local caret = acc.Header:FindFirstChild("Caret")
      mock.resetTweens()
      acc:Toggle()
      h.expect(caret.ImageColor3).toBe(theme.Colors.foreground)
      h.expect(caret.Rotation).toBe(90)
      h.expect(acc.Container.AutomaticSize.Name).toBe("Y")
      acc:Toggle()
      h.expect(caret.ImageColor3).toBe(theme.Colors.mutedForeground)
      h.expect(acc.Container.Size.Y.Offset).toBe(34)
      h.expect(mock.tweenCount()).toBe(0)
    end)
  end)
end)

h.run()
