local h = require("tests.helper")
local R = h.loadLib()
local Acrylic, Theme, Create = R.Acrylic, R.Theme, R.Create
local FX = Theme.MODE_EFFECTS

local function countClass(inst, cls)
  local n = 0
  for _, c in ipairs(inst:GetChildren()) do if c.ClassName == cls then n = n + 1 end end
  return n
end
-- Fresh instance per test so applyMode never leaks into the module-level Theme other tests share.
local function themed(mode, over)
  local t = Theme.new(over)
  if mode then Theme.applyMode(t, mode) end
  return t
end

h.describe("acrylic", function()
  h.it("decorate adds translucent fill + sheen + stroke + noise layer", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    h.expect(f.BackgroundColor3.R8).toBe(24)          -- card
    h.expect(f.BackgroundTransparency).toBe(0.12)     -- frosted (translucent but readable)
    h.expect(f:FindFirstChildOfClass("UIGradient") ~= nil).toBeTruthy()
    h.expect(f:FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    h.expect(f:FindFirstChild("AcrylicNoise") ~= nil).toBeTruthy()
  end)
  h.it("transparency option overrides the default frost", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { transparency = 0.25 })
    h.expect(f.BackgroundTransparency).toBe(0.25)
  end)
  h.it("solid has no gradient/noise and is opaque", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { solid = true })
    h.expect(f.BackgroundTransparency).toBe(0)
    h.expect(f:FindFirstChildOfClass("UIGradient")).toBeNil()
    h.expect(f:FindFirstChild("AcrylicNoise")).toBeNil()
  end)
  h.it("decorate twice does not duplicate stroke", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme); Acrylic.decorate(f, Theme)
    local strokes = 0
    for _, c in ipairs(f:GetChildren()) do if c.ClassName == "UIStroke" then strokes = strokes + 1 end end
    h.expect(strokes).toBe(1)
  end)
  h.it("base option overrides the fill colour", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { base = Theme.Colors.background })
    h.expect(f.BackgroundColor3.R8).toBe(Theme.Colors.background.R8)
  end)
end)

h.describe("acrylic layers (1.1)", function()
  h.it("non-solid frame gets AcrylicSheen and AcrylicNoise, each clipped by a UICorner at Radius.window", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    local noise, sheen = f:FindFirstChild("AcrylicNoise"), f:FindFirstChild("AcrylicSheen")
    h.expect(noise ~= nil).toBeTruthy()
    h.expect(sheen ~= nil).toBeTruthy()
    h.expect(noise:FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(Theme.Radius.window)
    h.expect(sheen:FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(Theme.Radius.window)
    h.expect(sheen.ClassName).toBe("Frame")
    h.expect(sheen.ZIndex).toBe(0)
    h.expect(sheen.Active).toBe(false)
    h.expect(sheen.BackgroundColor3.R).toBe(1)
    h.expect(sheen.BackgroundColor3.B).toBe(1)
    -- exactly one UIGradient directly under the frame: the sheen's own gradient is a grandchild
    h.expect(countClass(f, "UIGradient")).toBe(1)
    h.expect(countClass(sheen, "UIGradient")).toBe(1)
  end)
  h.it("radius opt sets the layer UICorner radius", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { radius = Theme.Radius.md })
    h.expect(f:FindFirstChild("AcrylicNoise"):FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(Theme.Radius.md)
    h.expect(f:FindFirstChild("AcrylicSheen"):FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(Theme.Radius.md)
  end)
  h.it("solid frame gets no AcrylicSheen either", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { solid = true })
    h.expect(f:FindFirstChild("AcrylicSheen")).toBeNil()
  end)
  h.it("noise reads theme.Acrylic tokens and the dark grain alpha/tint", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    local noise = f:FindFirstChild("AcrylicNoise")
    h.expect(noise.Image).toBe(Theme.Acrylic.noiseId)
    h.expect(noise.TileSize.X.Offset).toBe(Theme.Acrylic.tileSize)
    h.expect(noise.TileSize.Y.Offset).toBe(Theme.Acrylic.tileSize)
    h.expect(noise.ImageTransparency).toBe(FX.dark.grain)
    h.expect(noise.ImageColor3).toBe(FX.dark.grainTint) -- identity
    h.expect(noise.ZIndex).toBe(0)
  end)
  h.it("noiseId '' disables the grain layer", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, themed(nil, { Acrylic = { noiseId = "" } }))
    h.expect(f:FindFirstChild("AcrylicNoise")).toBeNil()
    h.expect(f:FindFirstChild("AcrylicSheen") ~= nil).toBeTruthy()
  end)
  h.it("dark sheen gradient multiplies the fill: keypoint[1] is white (sheenTop), keypoint[2] is sheenBottom", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { base = Theme.Colors.background })
    local grad = f:FindFirstChildOfClass("UIGradient")
    h.expect(grad.Rotation).toBe(90)
    h.expect(grad.Color.color[1].Time).toBe(0)
    h.expect(grad.Color.color[1].Value).toBe(FX.dark.sheenTop)     -- identity, R8 255
    h.expect(grad.Color.color[1].Value.R8).toBe(255)
    h.expect(grad.Color.color[2].Time).toBe(1)
    h.expect(grad.Color.color[2].Value).toBe(FX.dark.sheenBottom)  -- identity
  end)
  h.it("light sheen falls back to theme.Colors.card (identity multiplier) at the top", function()
    local t = themed("light")
    local f = Create("Frame", {})
    Acrylic.decorate(f, t, { base = t.Colors.background })
    local grad = f:FindFirstChildOfClass("UIGradient")
    h.expect(grad.Color.color[1].Value).toBe(t.Colors.card)
    h.expect(grad.Color.color[1].Value).toBe(Theme.PALETTES.light.card)
    h.expect(grad.Color.color[2].Value).toBe(FX.light.sheenBottom)
  end)
  h.it("sheen highlight band: top alpha scaled by (1 - transparency), band at Acrylic.highlightBand, visible in dark", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { transparency = 0.6 })
    local sheen = f:FindFirstChild("AcrylicSheen")
    local g = sheen:FindFirstChildOfClass("UIGradient")
    h.expect(g.Rotation).toBe(90)
    local kp = g.Transparency.keypoints
    h.expect(kp[1].Time).toBe(0)
    h.expect(kp[1].Value).toBeCloseTo(1 - (1 - FX.dark.highlight) * (1 - 0.6))
    h.expect(kp[2].Time).toBe(Theme.Acrylic.highlightBand)
    h.expect(kp[2].Value).toBe(1)
    h.expect(kp[3].Time).toBe(1)
    h.expect(kp[3].Value).toBe(1)
    h.expect(sheen.Visible).toBe(true)
    h.expect(sheen.BackgroundTransparency).toBe(0)
  end)
  h.it("light mode hides the sheen (highlight == 1) and tints the grain black at the light alpha", function()
    local t = themed("light")
    local f = Create("Frame", {})
    Acrylic.decorate(f, t)
    h.expect(f:FindFirstChild("AcrylicSheen").Visible).toBe(false)
    local noise = f:FindFirstChild("AcrylicNoise")
    h.expect(noise.ImageTransparency).toBe(FX.light.grain)
    h.expect(noise.ImageColor3).toBe(FX.light.grainTint)
  end)
  h.it("padInset offsets the noise/sheen layers by -p and grows them by 2p so they reach the padded edge", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { padInset = 8 })
    for _, name in ipairs({ "AcrylicNoise", "AcrylicSheen" }) do
      local layer = f:FindFirstChild(name)
      h.expect(layer.Position.X.Offset).toBe(-8)
      h.expect(layer.Position.Y.Offset).toBe(-8)
      h.expect(layer.Size.X.Scale).toBe(1)
      h.expect(layer.Size.X.Offset).toBe(16)
      h.expect(layer.Size.Y.Scale).toBe(1)
      h.expect(layer.Size.Y.Offset).toBe(16)
    end
  end)
  h.it("layers without padInset span the frame exactly", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    local layer = f:FindFirstChild("AcrylicSheen")
    h.expect(layer.Position.Y.Offset).toBe(0)
    h.expect(layer.Size.X.Offset).toBe(0)
    h.expect(layer.Size.Y.Scale).toBe(1)
  end)
end)

h.describe("acrylic stroke + edge (F10 / 2.4)", function()
  h.it("stroke defaults to theme.Acrylic.strokeAlpha and strokeAlpha opt writes UIStroke.Transparency", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    local s = f:FindFirstChildOfClass("UIStroke")
    h.expect(s.Transparency).toBe(Theme.Acrylic.strokeAlpha)
    h.expect(s.Transparency).toBe(0.3)
    h.expect(s.Color).toBe(Theme.Colors.border) -- identity
    h.expect(s.Thickness).toBe(1)
    local g = Create("Frame", {})
    Acrylic.decorate(g, Theme, { solid = true, strokeAlpha = Theme.Stroke.floating })
    h.expect(g:FindFirstChildOfClass("UIStroke").Transparency).toBe(0)
  end)
  h.it("decorate again re-applies the stroke alpha on the existing stroke", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { strokeAlpha = 0.5 })
    Acrylic.decorate(f, Theme, { strokeAlpha = 0.1 })
    h.expect(countClass(f, "UIStroke")).toBe(1)
    h.expect(f:FindFirstChildOfClass("UIStroke").Transparency).toBe(0.1)
  end)
  h.it("edge=true adds exactly one rim UIGradient under the UIStroke and an AcrylicGlint, still one UIStroke", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { edge = true })
    local s = f:FindFirstChildOfClass("UIStroke")
    h.expect(countClass(f, "UIStroke")).toBe(1)
    h.expect(countClass(f, "UIGradient")).toBe(1) -- the acrylic sheen stays the only direct-child gradient
    h.expect(countClass(s, "UIGradient")).toBe(1)
    local rim = s:FindFirstChildOfClass("UIGradient")
    h.expect(rim.Rotation).toBe(90)
    h.expect(rim.Transparency.keypoints[1].Value).toBe(FX.dark.edgeTop)
    h.expect(rim.Transparency.keypoints[2].Value).toBe(FX.dark.edgeBottom)
    h.expect(s.Color).toBe(Theme.Colors.border) -- rim never touches the stroke colour
    local glint = f:FindFirstChild("AcrylicGlint")
    h.expect(glint ~= nil).toBeTruthy()
    h.expect(glint.ClassName).toBe("Frame")
    h.expect(glint.BackgroundTransparency).toBe(FX.dark.glint)
    h.expect(glint.Visible).toBe(true)
    h.expect(glint.ZIndex).toBe(0)
    h.expect(glint.Active).toBe(false)
    h.expect(glint.BackgroundColor3.R).toBe(1)
    local r = Theme.Radius.window
    h.expect(glint.Size.X.Scale).toBe(1)
    h.expect(glint.Size.X.Offset).toBe(-2 * r)
    h.expect(glint.Size.Y.Scale).toBe(0)
    h.expect(glint.Size.Y.Offset).toBe(1)
    h.expect(glint.Position.X.Offset).toBe(r)
    h.expect(glint.Position.Y.Offset).toBe(0)
    local gg = glint:FindFirstChildOfClass("UIGradient")
    h.expect(gg ~= nil).toBeTruthy()
    h.expect(gg.Rotation).toBe(0)
    local kp = gg.Transparency.keypoints
    h.expect(#kp).toBe(4)
    h.expect(kp[1].Value).toBe(1); h.expect(kp[2].Value).toBe(0); h.expect(kp[3].Value).toBe(0); h.expect(kp[4].Value).toBe(1)
    h.expect(kp[2].Time).toBeCloseTo(1 - kp[3].Time) -- fades symmetrically at both ends
  end)
  h.it("edge=true twice keeps one rim and one glint", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { edge = true }); Acrylic.decorate(f, Theme, { edge = true })
    h.expect(countClass(f:FindFirstChildOfClass("UIStroke"), "UIGradient")).toBe(1)
    local n = 0
    for _, c in ipairs(f:GetChildren()) do if c.Name == "AcrylicGlint" then n = n + 1 end end
    h.expect(n).toBe(1)
  end)
  h.it("edge glint follows padInset and radius; a solid host gets the rim but no glint frame (list layouts)", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { edge = true, padInset = 8, radius = Theme.Radius.md })
    local glint, r = f:FindFirstChild("AcrylicGlint"), Theme.Radius.md
    h.expect(glint.Position.X.Offset).toBe(r - 8)
    h.expect(glint.Position.Y.Offset).toBe(-8)
    h.expect(glint.Size.X.Offset).toBe(16 - 2 * r)
    local card = Create("Frame", {})
    Acrylic.decorate(card, Theme, { solid = true, edge = true })
    h.expect(countClass(card:FindFirstChildOfClass("UIStroke"), "UIGradient")).toBe(1)
    h.expect(card:FindFirstChild("AcrylicGlint")).toBeNil()
  end)
  h.it("light mode hides the glint (glint == 1) and paints the light rim alphas", function()
    local t = themed("light")
    local f = Create("Frame", {})
    Acrylic.decorate(f, t, { edge = true })
    h.expect(f:FindFirstChild("AcrylicGlint").Visible).toBe(false)
    local rim = f:FindFirstChildOfClass("UIStroke"):FindFirstChildOfClass("UIGradient")
    h.expect(rim.Transparency.keypoints[1].Value).toBe(FX.light.edgeTop)
  end)
end)

h.describe("acrylic.reskin (F10)", function()
  h.it("after applyMode swaps fill, stroke colour, keypoints, grain alpha/tint, sheen + glint visibility, rim", function()
    local t = themed()
    local f = Create("Frame", {})
    Acrylic.decorate(f, t, { base = t.Colors.background, edge = true })
    Theme.applyMode(t, "light")
    Acrylic.reskin(f, t, { base = t.Colors.background, edge = true })
    h.expect(f.BackgroundColor3).toBe(t.Colors.background)
    h.expect(f.BackgroundColor3).toBe(Theme.PALETTES.light.background)
    local s = f:FindFirstChildOfClass("UIStroke")
    h.expect(s.Color).toBe(Theme.PALETTES.light.border)
    h.expect(s.Transparency).toBe(t.Acrylic.strokeAlpha)
    local grad = f:FindFirstChildOfClass("UIGradient")
    h.expect(grad.Color.color[1].Value).toBe(t.Colors.card)
    h.expect(grad.Color.color[2].Value).toBe(FX.light.sheenBottom)
    local noise = f:FindFirstChild("AcrylicNoise")
    h.expect(noise.ImageTransparency).toBe(FX.light.grain)
    h.expect(noise.ImageColor3).toBe(FX.light.grainTint)
    h.expect(f:FindFirstChild("AcrylicSheen").Visible).toBe(false)
    h.expect(f:FindFirstChild("AcrylicGlint").Visible).toBe(false)
    h.expect(f:FindFirstChild("AcrylicGlint").BackgroundTransparency).toBe(FX.light.glint)
    local rim = s:FindFirstChildOfClass("UIGradient")
    h.expect(rim.Transparency.keypoints[2].Value).toBe(FX.light.edgeBottom)
    h.expect(countClass(s, "UIGradient")).toBe(1)
    -- and back to dark
    Theme.applyMode(t, "dark")
    Acrylic.reskin(f, t, { base = t.Colors.background })
    h.expect(grad.Color.color[1].Value).toBe(FX.dark.sheenTop)
    h.expect(noise.ImageColor3).toBe(FX.dark.grainTint)
    h.expect(f:FindFirstChild("AcrylicSheen").Visible).toBe(true)
    h.expect(f:FindFirstChild("AcrylicGlint").Visible).toBe(true) -- existing glint re-painted even without edge opt
    h.expect(rim.Transparency.keypoints[1].Value).toBe(FX.dark.edgeTop)
  end)
  h.it("keeps the host transparency the owner set unless opts.transparency is given; sheen alpha follows it", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    f.BackgroundTransparency = 0.5 -- window SetTransparency writes Main directly
    Acrylic.reskin(f, Theme, { base = Theme.Colors.background })
    h.expect(f.BackgroundTransparency).toBe(0.5)
    local kp = f:FindFirstChild("AcrylicSheen"):FindFirstChildOfClass("UIGradient").Transparency.keypoints
    h.expect(kp[1].Value).toBeCloseTo(1 - (1 - FX.dark.highlight) * 0.5)
    Acrylic.reskin(f, Theme, { transparency = 0.2 })
    h.expect(f.BackgroundTransparency).toBe(0.2)
    h.expect(f.BackgroundColor3).toBe(Theme.Colors.card) -- base omitted -> card
  end)
  h.it("strokeAlpha opt writes UIStroke.Transparency; never adds layers to a solid host; adds nothing to a bare frame", function()
    local card = Create("Frame", {})
    Acrylic.decorate(card, Theme, { solid = true })
    Acrylic.reskin(card, Theme, { solid = true, strokeAlpha = 0 })
    h.expect(card:FindFirstChildOfClass("UIStroke").Transparency).toBe(0)
    h.expect(card:FindFirstChild("AcrylicNoise")).toBeNil()
    h.expect(card:FindFirstChild("AcrylicSheen")).toBeNil()
    h.expect(card:FindFirstChildOfClass("UIGradient")).toBeNil()
    h.expect(card.BackgroundTransparency).toBe(0)
    local bare = Create("Frame", {})
    Acrylic.reskin(bare, Theme)
    h.expect(#bare:GetChildren()).toBe(0)
    h.expect(bare.BackgroundColor3).toBe(Theme.Colors.card)
  end)
  h.it("edge=true on reskin adds the rim/glint to a host decorated without them (opt-in later), idempotently", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    Acrylic.reskin(f, Theme, { edge = true }); Acrylic.reskin(f, Theme, { edge = true })
    h.expect(countClass(f:FindFirstChildOfClass("UIStroke"), "UIGradient")).toBe(1)
    h.expect(f:FindFirstChild("AcrylicGlint") ~= nil).toBeTruthy()
    h.expect(countClass(f, "UIStroke")).toBe(1)
    h.expect(countClass(f, "UIGradient")).toBe(1)
  end)
  h.it("returns the frame", function()
    local f = Create("Frame", {})
    h.expect(Acrylic.decorate(f, Theme)).toBe(f)
    h.expect(Acrylic.reskin(f, Theme)).toBe(f)
  end)
end)

h.run()
