local h = require("tests.helper")
local Animate = h.loadLib().Animate

h.describe("animate", function()
  h.it("info builds TweenInfo with Quart/Out defaults", function()
    local i = Animate.info(0.18)
    h.expect(i.Time).toBe(0.18)
    h.expect(i.EasingStyle.Name).toBe("Quart")
    h.expect(i.EasingDirection.Name).toBe("Out")
  end)
  h.it("to() plays a tween and applies goal", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "fast", { BackgroundTransparency = 0.15 })
    h.expect(h.mock.lastTween.played).toBeTruthy()
    h.expect(f.BackgroundTransparency).toBe(0.15)
  end)
  h.it("resolves motion-key durations", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "slow", { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.28)
  end)
  h.it("pop adds a UIScale and tweens it to 1 with Back/Out", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.pop(f, "base")
    local us = f:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(h.mock.lastTween.Instance).toBe(us)
    h.expect(h.mock.lastTween.Goal.Scale).toBe(1)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
  end)
  h.it("setEnabled(false) applies goal instantly and returns an immediate-complete stub", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.setEnabled(false)
    local fired = false
    local tw = Animate.to(f, "fast", { BackgroundTransparency = 0.4 })
    tw.Completed:Connect(function() fired = true end)
    h.expect(f.BackgroundTransparency).toBe(0.4)
    h.expect(fired).toBe(true)
    Animate.setEnabled(true)
  end)
  h.it("toThen runs onComplete once and applies goal (enabled)", function()
    local f = h.roblox.Instance.new("Frame")
    local n = 0
    Animate.toThen(f, "fast", { X = 2 }, function() n = n + 1 end)
    h.expect(f.X).toBe(2)
    h.expect(n).toBe(1)
  end)
  h.it("toThen runs onComplete once and applies goal (disabled)", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.setEnabled(false)
    local n = 0
    Animate.toThen(f, "fast", { X = 5 }, function() n = n + 1 end)
    h.expect(f.X).toBe(5)
    h.expect(n).toBe(1)
    Animate.setEnabled(true)
  end)
  h.it("springTo tweens with Back/Out and applies goal", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.springTo(f, "base", { Scale = 1 })
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
    h.expect(h.mock.lastTween.Info.EasingDirection.Name).toBe("Out")
    h.expect(f.Scale).toBe(1)
  end)
  h.it("rotateTo sets a Rotation goal with a Back default", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.rotateTo(f, "base", 90)
    h.expect(f.Rotation).toBe(90)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
  end)
end)

-- ---- F3 helper pack -------------------------------------------------------------------------
local R = h.loadLib()
local Theme = R.Theme
local Motion = Theme.Motion
-- F1 lands the new Motion tokens in parallel; read them through the same fallbacks animate.lua
-- uses so this file is green before and after that edit.
local SPIN, EXIT, EXIT_SCALE, POP_SLIDE = Motion.spin or 0.8, Motion.exit or 0.14, Motion.exitScale or 0.96, Motion.popSlide or 6

-- A fresh copy of core/animate.lua (bypasses the requireModule cache) so the explicit
-- reduced-motion flag can be observed from its pristine state, independent of test order.
local function freshAnimate()
  local chunk = assert(loadfile("core/animate.lua"))
  setfenv(chunk, setmetatable({}, { __index = function(_, k)
    if h.roblox[k] ~= nil then return h.roblox[k] end
    return _G[k]
  end }))
  local A = chunk()
  A.Init({ Theme = Theme })
  return A
end

-- Snapshot each tweened property at Create time (before the synchronous mock Play overwrites it
-- with the goal) so a recipe's pre-set "from" state can be asserted, not just its goal.
local function captureFrom(fn)
  local TS = h.roblox.game:GetService("TweenService")
  local orig = TS.Create
  local from = {}
  TS.Create = function(self, inst, info, goal)
    local snap = {}
    for k in pairs(goal) do snap[k] = inst[k] end
    from[#from + 1] = { Instance = inst, From = snap }
    return orig(self, inst, info, goal)
  end
  local ok, err = pcall(fn)
  TS.Create = orig
  if not ok then error(err, 0) end
  return from
end

local function frameAt(xo, yo)
  local f = h.roblox.Instance.new("Frame")
  f.Position = h.roblox.UDim2.new(0, xo, 0, yo)
  return f
end

h.describe("animate.info/delay", function()
  h.it("info(dur, style, dir, delay) forwards delay and pins RepeatCount 0 / Reverses false", function()
    local i = Animate.info(0.2, nil, nil, 0.05)
    h.expect(i.Time).toBe(0.2)
    h.expect(i.EasingStyle.Name).toBe("Quart")
    h.expect(i.EasingDirection.Name).toBe("Out")
    h.expect(i.RepeatCount).toBe(0)
    h.expect(i.Reverses).toBe(false)
    h.expect(i.DelayTime).toBe(0.05)
  end)
  h.it("info without delay yields DelayTime 0 (never nil)", function()
    h.expect(Animate.info(0.2).DelayTime).toBe(0)
    h.expect(Animate.info(0.2, Animate.EASING.pop, Animate.DIR.In).DelayTime).toBe(0)
  end)
  h.it("to() without delay still yields DelayTime 0", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "fast", { X = 1 })
    h.expect(h.mock.lastTween.Info.DelayTime).toBe(0)
    Animate.to(f, "fast", { X = 2 }, Animate.EASING.smooth, Animate.DIR.InOut)
    h.expect(h.mock.lastTween.Info.DelayTime).toBe(0)
  end)
  h.it("to() forwards a trailing delay into Info.DelayTime", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "fast", { X = 1 }, nil, nil, 0.1)
    h.expect(h.mock.lastTween.Info.DelayTime).toBe(0.1)
    h.expect(h.mock.lastTween.Info.Time).toBe(0.12)
    h.expect(f.X).toBe(1)
  end)
  h.it("toThen forwards a trailing delay and still runs onComplete once", function()
    local f = h.roblox.Instance.new("Frame")
    local n = 0
    Animate.toThen(f, "base", { X = 3 }, function() n = n + 1 end, nil, nil, 0.07)
    h.expect(h.mock.lastTween.Info.DelayTime).toBe(0.07)
    h.expect(f.X).toBe(3)
    h.expect(n).toBe(1)
  end)
  h.it("a nil duration resolves to the 0.18 default instead of a nil TweenInfo time", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, nil, { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.18)
  end)
end)

h.describe("animate.EASING/DIR", function()
  h.it("keeps pop/smooth and adds enter/exit/snap", function()
    h.expect(Animate.EASING.pop.Name).toBe("Back")
    h.expect(Animate.EASING.smooth.Name).toBe("Quint")
    h.expect(Animate.EASING.enter.Name).toBe("Quint")
    h.expect(Animate.EASING.exit.Name).toBe("Quart")
    h.expect(Animate.EASING.snap.Name).toBe(h.roblox.Enum.EasingStyle.Quad and "Quad" or "Quart")
  end)
  h.it("DIR exposes In/Out/InOut", function()
    h.expect(Animate.DIR.In.Name).toBe("In")
    h.expect(Animate.DIR.Out.Name).toBe("Out")
    h.expect(Animate.DIR.InOut.Name).toBe("InOut")
  end)
end)

h.describe("animate.useMotion", function()
  h.it("useMotion table wins over Theme.Motion for resolve()", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.useMotion({ base = 0.5 })
    Animate.to(f, "base", { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.5)
    Animate.useMotion(nil)
    Animate.to(f, "base", { X = 2 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.18)
  end)
  h.it("falls back useMotion -> Theme.Motion -> 0.18 and never throws on an unknown token", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.useMotion({ base = 0.5 })
    Animate.to(f, "slow", { X = 1 })                  -- missing in the override: Theme.Motion
    h.expect(h.mock.lastTween.Info.Time).toBe(0.28)
    Animate.to(f, "no_such_token", { X = 2 })         -- missing everywhere: 0.18
    h.expect(h.mock.lastTween.Info.Time).toBe(0.18)
    Animate.useMotion(nil)
    Animate.to(f, "no_such_token", { X = 3 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.18)
  end)
  h.it("a non-number token value is skipped, not handed to TweenInfo", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.useMotion({ base = { amp = 3 } })
    Animate.to(f, "base", { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.18) -- Theme.Motion.base
    Animate.useMotion(nil)
  end)
end)

h.describe("animate.reducedMotion", function()
  h.it("applyDefault writes enabled only while no explicit setEnabled happened", function()
    local A = freshAnimate()
    h.expect(A.isExplicit()).toBe(false)
    h.expect(A.isEnabled()).toBe(true)
    A.applyDefault(false)
    h.expect(A.isEnabled()).toBe(false)
    h.expect(A.isExplicit()).toBe(false)
    A.applyDefault(true)
    h.expect(A.isEnabled()).toBe(true)
  end)
  h.it("setEnabled marks explicit and applyDefault no longer overrides it", function()
    local A = freshAnimate()
    A.setEnabled(false)
    h.expect(A.isExplicit()).toBe(true)
    A.applyDefault(true)
    h.expect(A.isEnabled()).toBe(false)
    A.setEnabled(true)
    A.applyDefault(false)
    h.expect(A.isEnabled()).toBe(true)
  end)
  h.it("applyDefault returns the effective state", function()
    local A = freshAnimate()
    h.expect(A.applyDefault(false)).toBe(false)
    A.setEnabled(true)
    h.expect(A.applyDefault(false)).toBe(true)
  end)
end)

h.describe("animate.loop", function()
  h.it("loop plays an endless Linear/InOut tween and returns a Cancel handle", function()
    local f = h.roblox.Instance.new("Frame")
    h.mock.resetTweens()
    local hd = Animate.loop(f, 0.5, { X = 1 })
    local tw = h.mock.tweensFor(f)[1]
    h.expect(tw ~= nil).toBeTruthy()
    h.expect(tw.Info.Time).toBe(0.5)
    h.expect(tw.Info.EasingStyle.Name).toBe("Linear")
    h.expect(tw.Info.EasingDirection.Name).toBe("InOut")
    h.expect(tw.Info.RepeatCount).toBe(-1)
    h.expect(tw.Info.Reverses).toBe(false)
    h.expect(tw.Info.DelayTime).toBe(0)
    h.expect(tw.played).toBe(true)
    h.expect(f.X).toBe(1)
    h.expect(type(hd.Cancel)).toBe("function")
    hd.Cancel()
    h.expect(tw.cancelled).toBe(true)
  end)
  h.it("loop forwards style, reverses and repeatCount and resolves token durations", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.loop(f, "slow", { X = 1 }, Animate.EASING.smooth, true, 3)
    local i = h.mock.lastTween.Info
    h.expect(i.Time).toBe(0.28)
    h.expect(i.EasingStyle.Name).toBe("Quint")
    h.expect(i.RepeatCount).toBe(3)
    h.expect(i.Reverses).toBe(true)
  end)
  h.it("loop treats a non-boolean reverses as false", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.loop(f, 0.3, { X = 1 }, nil, "yes")
    h.expect(h.mock.lastTween.Info.Reverses).toBe(false)
  end)
  h.it("loop under reduced motion creates no tween, applies the goal and returns a no-op handle", function()
    h.withReducedMotion(R, function()
      local f = h.roblox.Instance.new("Frame")
      h.mock.resetTweens()
      local hd = Animate.loop(f, 0.5, { X = 7 })
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(f.X).toBe(7)
      h.expect(type(hd.Cancel)).toBe("function")
      hd.Cancel()
      h.expect(f.X).toBe(7)
    end)
  end)
  h.it("a reversing loop under reduced motion leaves the instance at rest (untouched)", function()
    h.withReducedMotion(R, function()
      local f = h.roblox.Instance.new("Frame")
      f.X = 1
      h.mock.resetTweens()
      Animate.loop(f, 0.5, { X = 1.2 }, nil, true)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(f.X).toBe(1)
    end)
  end)
end)

h.describe("animate.spin", function()
  h.it("spin loops Rotation 0 -> 360 Linear over Motion.spin and Cancel resets Rotation 0", function()
    local img = h.roblox.Instance.new("ImageLabel")
    img.Rotation = 45
    h.mock.resetTweens()
    local hd = Animate.spin(img)
    local tw = h.mock.tweensFor(img)[1]
    h.expect(tw.Goal.Rotation).toBe(360)
    h.expect(tw.Info.Time).toBe(SPIN)
    h.expect(tw.Info.EasingStyle.Name).toBe("Linear")
    h.expect(tw.Info.RepeatCount).toBe(-1)
    h.expect(tw.Info.Reverses).toBe(false)
    h.expect(img.Rotation).toBe(360) -- mock applies the goal once
    hd.Cancel()
    h.expect(tw.cancelled).toBe(true)
    h.expect(img.Rotation).toBe(0)
  end)
  h.it("spin starts from Rotation 0 and accepts an explicit period", function()
    local img = h.roblox.Instance.new("ImageLabel")
    img.Rotation = 45
    local from = captureFrom(function() Animate.spin(img, 1.5) end)
    h.expect(from[1].From.Rotation).toBe(0)
    h.expect(h.mock.lastTween.Info.Time).toBe(1.5)
  end)
  h.it("spin under reduced motion is a no-op at Rotation 0 whose Cancel also resets", function()
    h.withReducedMotion(R, function()
      local img = h.roblox.Instance.new("ImageLabel")
      img.Rotation = 45
      h.mock.resetTweens()
      local hd = Animate.spin(img)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(img.Rotation).toBe(0)
      img.Rotation = 10
      hd.Cancel()
      h.expect(img.Rotation).toBe(0)
    end)
  end)
end)

h.describe("animate.pulse", function()
  h.it("pulse is a reversing loop, endless by default", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.pulse(f, "base", { X = 1.06 })
    local i = h.mock.lastTween.Info
    h.expect(i.Reverses).toBe(true)
    h.expect(i.RepeatCount).toBe(-1)
    h.expect(i.Time).toBe(0.18)
    h.expect(i.EasingStyle.Name).toBe("Linear")
  end)
  h.it("pulse forwards style and a finite cycle count", function()
    local f = h.roblox.Instance.new("Frame")
    local hd = Animate.pulse(f, 0.4, { X = 1.06 }, Animate.EASING.smooth, 2)
    local i = h.mock.lastTween.Info
    h.expect(i.RepeatCount).toBe(2)
    h.expect(i.EasingStyle.Name).toBe("Quint")
    hd.Cancel()
    h.expect(h.mock.lastTween.cancelled).toBe(true)
  end)
  h.it("pulse under reduced motion creates no tween and leaves the instance untouched", function()
    h.withReducedMotion(R, function()
      local f = h.roblox.Instance.new("Frame")
      f.X = 1
      h.mock.resetTweens()
      local hd = Animate.pulse(f, 0.4, { X = 1.06 })
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(f.X).toBe(1)
      h.expect(type(hd.Cancel)).toBe("function")
    end)
  end)
end)

h.describe("animate.exitTo", function()
  h.it("exitTo tweens Quart/In and runs onDone once", function()
    local f = h.roblox.Instance.new("Frame")
    local n = 0
    Animate.exitTo(f, "fast", { X = 0 }, function() n = n + 1 end)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Quart")
    h.expect(h.mock.lastTween.Info.EasingDirection.Name).toBe("In")
    h.expect(h.mock.lastTween.Info.Time).toBe(0.12)
    h.expect(f.X).toBe(0)
    h.expect(n).toBe(1)
  end)
  h.it("exitTo under reduced motion applies instantly and still runs onDone", function()
    h.withReducedMotion(R, function()
      local f = h.roblox.Instance.new("Frame")
      local n = 0
      h.mock.resetTweens()
      Animate.exitTo(f, "fast", { X = 0 }, function() n = n + 1 end)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(f.X).toBe(0)
      h.expect(n).toBe(1)
    end)
  end)
end)

h.describe("animate.chain", function()
  h.it("chain runs steps in order with per-step style/dir/delay, then onDone once", function()
    local a, b = h.roblox.Instance.new("Frame"), h.roblox.Instance.new("Frame")
    local order, n = {}, 0
    h.mock.resetTweens()
    Animate.chain({
      { a, "fast", { X = 1 } },
      { b, 0.3, { X = 2 }, Animate.EASING.pop, Animate.DIR.InOut, 0.05 },
      { a, "base", { X = 3 }, nil, nil, "stagger_missing" },
    }, function() n = n + 1; order[#order + 1] = "done" end)
    h.expect(h.mock.tweenCount()).toBe(3)
    local t1, t2, t3 = h.mock.tweens[1], h.mock.tweens[2], h.mock.tweens[3]
    h.expect(t1.Instance).toBe(a); h.expect(t1.Goal.X).toBe(1); h.expect(t1.Info.Time).toBe(0.12)
    h.expect(t1.Info.EasingStyle.Name).toBe("Quart"); h.expect(t1.Info.DelayTime).toBe(0)
    h.expect(t2.Instance).toBe(b); h.expect(t2.Info.Time).toBe(0.3)
    h.expect(t2.Info.EasingStyle.Name).toBe("Back"); h.expect(t2.Info.EasingDirection.Name).toBe("InOut")
    h.expect(t2.Info.DelayTime).toBe(0.05)
    h.expect(t3.Instance).toBe(a); h.expect(t3.Goal.X).toBe(3)
    h.expect(t3.Info.DelayTime).toBe(0) -- unknown delay token -> 0, not an error
    h.expect(a.X).toBe(3); h.expect(b.X).toBe(2)
    h.expect(n).toBe(1)
  end)
  h.it("an empty chain calls onDone immediately", function()
    local n = 0
    Animate.chain({}, function() n = n + 1 end)
    h.expect(n).toBe(1)
    Animate.chain(nil, function() n = n + 1 end)
    h.expect(n).toBe(2)
    Animate.chain({}) -- no onDone: must not throw
  end)
  h.it("chain under reduced motion applies every goal without tweens and runs onDone once", function()
    h.withReducedMotion(R, function()
      local a, b = h.roblox.Instance.new("Frame"), h.roblox.Instance.new("Frame")
      local n = 0
      h.mock.resetTweens()
      Animate.chain({ { a, "fast", { X = 1 } }, { b, "fast", { X = 2 } } }, function() n = n + 1 end)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(a.X).toBe(1); h.expect(b.X).toBe(2)
      h.expect(n).toBe(1)
    end)
  end)
end)

h.describe("animate.popIn/popOut", function()
  h.it("popIn('down') grows a UIScale from exitScale (Back/Out, base) and slides up into place (Quart/Out, fast)", function()
    local f = frameAt(10, 20)
    h.mock.resetTweens()
    local from = captureFrom(function() Animate.popIn(f, "down") end)
    local us = f:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    local scaleTw = h.mock.tweensFor(us)[1]
    local posTw = h.mock.tweensFor(f)[1]
    h.expect(scaleTw ~= nil).toBeTruthy()
    h.expect(posTw ~= nil).toBeTruthy()
    h.expect(scaleTw.Goal.Scale).toBe(1)
    h.expect(scaleTw.Info.EasingStyle.Name).toBe("Back")
    h.expect(scaleTw.Info.EasingDirection.Name).toBe("Out")
    h.expect(scaleTw.Info.Time).toBe(0.18)
    h.expect(posTw.Info.EasingStyle.Name).toBe("Quart")
    h.expect(posTw.Info.EasingDirection.Name).toBe("Out")
    h.expect(posTw.Info.Time).toBe(0.12)
    -- pre-set "from" state: scale exitScale, Position nudged popSlide px above the target
    local fromScale, fromPos
    for _, s in ipairs(from) do
      if s.Instance == us then fromScale = s.From.Scale end
      if s.Instance == f then fromPos = s.From.Position end
    end
    h.expect(fromScale).toBeCloseTo(EXIT_SCALE)
    h.expect(fromPos.Y.Offset).toBe(20 - POP_SLIDE)
    h.expect(fromPos.X.Offset).toBe(10)
    -- final state is the caller's Position (layout code reads it synchronously)
    h.expect(us.Scale).toBe(1)
    h.expect(f.Position.X.Offset).toBe(10)
    h.expect(f.Position.Y.Offset).toBe(20)
  end)
  h.it("popIn('up') starts popSlide px below the target; nil edge behaves like 'down'", function()
    local f = frameAt(0, 100)
    local from = captureFrom(function() Animate.popIn(f, "up") end)
    local fromPos
    for _, s in ipairs(from) do if s.Instance == f then fromPos = s.From.Position end end
    h.expect(fromPos.Y.Offset).toBe(100 + POP_SLIDE)
    h.expect(f.Position.Y.Offset).toBe(100)
    local g = frameAt(0, 100)
    from = captureFrom(function() Animate.popIn(g) end)
    for _, s in ipairs(from) do if s.Instance == g then fromPos = s.From.Position end end
    h.expect(fromPos.Y.Offset).toBe(100 - POP_SLIDE)
  end)
  h.it("popIn reuses an existing UIScale instead of adding a second one", function()
    local f = frameAt(0, 0)
    local us = h.roblox.Instance.new("UIScale"); us.Parent = f
    Animate.popIn(f, "down")
    local n = 0
    for _, c in ipairs(f:GetChildren()) do if c.ClassName == "UIScale" then n = n + 1 end end
    h.expect(n).toBe(1)
    h.expect(h.mock.tweensFor(us)[1] ~= nil).toBeTruthy()
  end)
  h.it("popIn on a frame without a Position only animates the scale", function()
    local f = h.roblox.Instance.new("Frame")
    h.mock.resetTweens()
    Animate.popIn(f, "down")
    h.expect(h.mock.tweenCount()).toBe(1)
    h.expect(f.Position).toBeNil()
    h.expect(f:FindFirstChildOfClass("UIScale").Scale).toBe(1)
  end)
  h.it("popIn under reduced motion sets Scale 1 instantly, leaves Position alone, no tweens", function()
    h.withReducedMotion(R, function()
      local f = frameAt(10, 20)
      h.mock.resetTweens()
      Animate.popIn(f, "down")
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(f:FindFirstChildOfClass("UIScale").Scale).toBe(1)
      h.expect(f.Position.Y.Offset).toBe(20)
    end)
  end)
  h.it("popOut shrinks the UIScale to exitScale (Quart/In over Motion.exit) then runs onDone", function()
    local f = frameAt(10, 20)
    Animate.popIn(f, "down")
    local us = f:FindFirstChildOfClass("UIScale")
    local n = 0
    h.mock.resetTweens()
    Animate.popOut(f, function() n = n + 1 end)
    h.expect(h.mock.tweenCount()).toBe(1)
    local tw = h.mock.tweensFor(us)[1]
    h.expect(tw.Goal.Scale).toBeCloseTo(EXIT_SCALE)
    h.expect(tw.Info.EasingStyle.Name).toBe("Quart")
    h.expect(tw.Info.EasingDirection.Name).toBe("In")
    h.expect(tw.Info.Time).toBeCloseTo(EXIT)
    h.expect(tw.Info.DelayTime).toBe(0)
    h.expect(n).toBe(1)
    h.expect(f.Position.Y.Offset).toBe(20) -- popOut never moves the frame
  end)
  h.it("popOut creates the UIScale when missing and tolerates a nil onDone", function()
    local f = frameAt(0, 0)
    Animate.popOut(f)
    local us = f:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(us.Scale).toBeCloseTo(EXIT_SCALE)
  end)
  h.it("popOut under reduced motion applies the scale instantly and still runs onDone", function()
    h.withReducedMotion(R, function()
      local f = frameAt(0, 0)
      local n = 0
      h.mock.resetTweens()
      Animate.popOut(f, function() n = n + 1 end)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(n).toBe(1)
      h.expect(f:FindFirstChildOfClass("UIScale").Scale).toBeCloseTo(EXIT_SCALE)
    end)
  end)
end)

h.run()
