local h = require("tests.helper")
local R = h.loadLib()
local Effects, Theme, Animate, Create = R.Effects, R.Theme, R.Animate, R.Create
local rb = h.roblox
local FX = Theme.MODE_EFFECTS
local SHADOW = "rbxassetid://1"

-- A theme with the 9-slice asset filled in (the default '' keeps every layer nil).
local function themed(mode, effect)
  local over = { shadowId = SHADOW }
  for k, v in pairs(effect or {}) do over[k] = v end
  local t = Theme.new({ Effect = over })
  if mode then Theme.applyMode(t, mode) end
  return t
end
local function frame() return rb.Instance.new("Frame") end
local function countClass(inst, cls)
  local n = 0
  for _, c in ipairs(inst:GetChildren()) do if c.ClassName == cls then n = n + 1 end end
  return n
end
-- Form-factor switches mirror tests/device_test.lua: touch-only + phone aspect = Mobile.
local function desktop()
  local uis, cam = rb.game:GetService("UserInputService"), rb.workspace.CurrentCamera
  uis.TouchEnabled = false; uis.MouseEnabled = true; h.mock.tenFoot = false
  cam.ViewportSize = rb.Vector2.new(1280, 720)
end
local function mobile()
  local uis, cam = rb.game:GetService("UserInputService"), rb.workspace.CurrentCamera
  uis.TouchEnabled = true; uis.MouseEnabled = false; h.mock.tenFoot = false
  cam.ViewportSize = rb.Vector2.new(320, 640)
end

h.describe("effects.shadow", function()
  h.it("returns nil while Effect.shadowId is '' (today's default)", function()
    h.expect(Effects.shadow(frame(), Theme.new(), { name = "S", zIndex = 0 })).toBeNil()
    h.expect(Effects.shadow(frame(), Theme, { name = "S", zIndex = 0 })).toBeNil()
  end)
  h.it("builds a filled 9-slice ImageLabel with the dark alpha, black tint and the given ZIndex", function()
    local t, p = themed(), frame()
    local s = Effects.shadow(p, t, { name = "WindowShadow", level = "window", zIndex = 0 })
    h.expect(s.ClassName).toBe("ImageLabel")
    h.expect(s.Name).toBe("WindowShadow")
    h.expect(s.Parent).toBe(p)
    h.expect(s.Image).toBe(SHADOW)
    h.expect(s.ScaleType).toBe(rb.Enum.ScaleType.Slice)
    h.expect(s.SliceCenter.Min.X).toBe(49); h.expect(s.SliceCenter.Min.Y).toBe(49)
    h.expect(s.SliceCenter.Max.X).toBe(450); h.expect(s.SliceCenter.Max.Y).toBe(450)
    h.expect(s.ImageColor3.R).toBe(0); h.expect(s.ImageColor3.G).toBe(0); h.expect(s.ImageColor3.B).toBe(0)
    h.expect(s.ImageTransparency).toBe(FX.dark.shadow)
    h.expect(s.AnchorPoint.X).toBe(0.5); h.expect(s.AnchorPoint.Y).toBe(0.5)
    h.expect(s.Active).toBe(false)
    h.expect(s.BackgroundTransparency).toBe(1)
    h.expect(s.ZIndex).toBe(0)
  end)
  h.it("reads the light alpha after applyMode and defaults ZIndex to 0 (below any host)", function()
    local s = Effects.shadow(frame(), themed("light"), { name = "S" })
    h.expect(s.ImageTransparency).toBe(FX.light.shadow)
    h.expect(s.ZIndex).toBe(0)
  end)
  h.it("skips SliceCenter when the Rect global is absent", function()
    local saved = rb.Rect
    rb.Rect = nil
    local ok, s = pcall(Effects.shadow, frame(), themed(), { name = "S" })
    rb.Rect = saved
    h.expect(ok).toBe(true)
    h.expect(s.SliceCenter).toBeNil()
    h.expect(s.ScaleType).toBe(rb.Enum.ScaleType.Slice)
  end)
  h.it("throws a clear error without a theme (no global theme is assumed)", function()
    h.expect(function() Effects.shadow(frame(), nil, { name = "S" }) end).toThrow("theme")
  end)
end)

h.describe("effects.place / mirror", function()
  h.it("place grows the size by 2*spread and centres on the host plus offsetY", function()
    local t = themed()
    local s = Effects.shadow(frame(), t, { name = "S", zIndex = 0 })
    Effects.place(s, 10, 20, 100, 50, "popover", t) -- popover: spread 18, offsetY 4
    h.expect(s.Size.X.Offset).toBe(136); h.expect(s.Size.Y.Offset).toBe(86)
    h.expect(s.Size.X.Scale).toBe(0); h.expect(s.Size.Y.Scale).toBe(0)
    h.expect(s.Position.X.Offset).toBe(60); h.expect(s.Position.Y.Offset).toBe(49)
  end)
  h.it("place/mirror/follow/lift/reskin tolerate a nil layer (shadowId '')", function()
    local t = Theme.new()
    h.expect(Effects.place(nil, 0, 0, 10, 10, "popover", t)).toBeNil()
    h.expect(Effects.mirror(nil, frame(), "window", t)).toBeNil()
    h.expect(Effects.follow(nil, frame(), "dialog", t)).toBeNil()
    h.expect(Effects.lift(nil, t, true)).toBeNil()
    h.expect(Effects.reskin(nil, t, "shadow")).toBeNil()
  end)
  h.it("an unknown level throws instead of silently placing nothing", function()
    local t = themed()
    local s = Effects.shadow(frame(), t, { name = "S" })
    h.expect(function() Effects.place(s, 0, 0, 10, 10, "banner", t) end).toThrow("unknown level")
  end)
  h.it("mirror copies Scale and adds 2*spread / offsetY for a centre-anchored host", function()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    host.AnchorPoint = rb.Vector2.new(0.5, 0.5)
    host.Position = rb.UDim2.new(0.5, 10, 0.5, 20)
    host.Size = rb.UDim2.new(0, 400, 0, 300)
    local s = Effects.shadow(p, t, { name = "WindowShadow", zIndex = 0 })
    Effects.mirror(s, host, "window", t) -- window: spread 28, offsetY 6
    h.expect(s.Size.X.Scale).toBe(0); h.expect(s.Size.X.Offset).toBe(456)
    h.expect(s.Size.Y.Scale).toBe(0); h.expect(s.Size.Y.Offset).toBe(356)
    h.expect(s.Position.X.Scale).toBe(0.5); h.expect(s.Position.X.Offset).toBe(10)
    h.expect(s.Position.Y.Scale).toBe(0.5); h.expect(s.Position.Y.Offset).toBe(26)
  end)
  h.it("mirror centres the shadow on a top-left-anchored host (FAB)", function()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    host.Position = rb.UDim2.new(0, 100, 0, 50)
    host.Size = rb.UDim2.new(0, 44, 0, 44)
    local s = Effects.shadow(p, t, { name = "FabShadow", zIndex = 0 })
    Effects.mirror(s, host, "control", t) -- control: spread 6, offsetY 0
    h.expect(s.Size.X.Offset).toBe(56); h.expect(s.Size.Y.Offset).toBe(56)
    h.expect(s.Position.X.Offset).toBe(122); h.expect(s.Position.Y.Offset).toBe(72)
  end)
  h.it("mirror falls back to the level given at creation and skips a host without geometry", function()
    local t, p = themed(), frame()
    local s = Effects.shadow(p, t, { name = "S", level = "tooltip" }) -- spread 10, offsetY 2
    local bare = frame()
    h.expect(Effects.mirror(s, bare, nil, t)).toBe(s)
    h.expect(s.Size).toBeNil()
    local host = frame(); host.Position = rb.UDim2.new(0, 0, 0, 0); host.Size = rb.UDim2.new(0, 20, 0, 10)
    Effects.mirror(s, host, nil, t)
    h.expect(s.Size.X.Offset).toBe(40); h.expect(s.Size.Y.Offset).toBe(30)
    h.expect(s.Position.Y.Offset).toBe(7)
  end)
end)

h.describe("effects.follow", function()
  h.it("skips the sync while Absolute* is nil and returns a maid-compatible handle", function()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    local s = Effects.shadow(p, t, { name = "DialogShadow", zIndex = 0 })
    local hd = Effects.follow(s, host, "dialog", t)
    h.expect(type(hd.Disconnect)).toBe("function")
    h.expect(s.Size).toBeNil(); h.expect(s.Position).toBeNil()
    host:GetPropertyChangedSignal("AbsoluteSize"):Fire()
    h.expect(s.Size).toBeNil()
  end)
  h.it("syncs after the test sets Absolute* and fires the property signal", function()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    local s = Effects.shadow(p, t, { name = "DialogShadow", zIndex = 0 })
    Effects.follow(s, host, "dialog", t) -- dialog: spread 32, offsetY 10
    host.AbsoluteSize = rb.Vector2.new(200, 100)
    host.AbsolutePosition = rb.Vector2.new(30, 40)
    host:GetPropertyChangedSignal("AbsoluteSize"):Fire()
    h.expect(s.Size.X.Offset).toBe(264); h.expect(s.Size.Y.Offset).toBe(164)
    h.expect(s.Position.X.Offset).toBe(130); h.expect(s.Position.Y.Offset).toBe(100)
    host.AbsolutePosition = rb.Vector2.new(50, 40)
    host:GetPropertyChangedSignal("AbsolutePosition"):Fire()
    h.expect(s.Position.X.Offset).toBe(150)
  end)
  h.it("subtracts the shared parent's screen origin so the shadow lands in local space", function()
    local t, p = themed(), frame()
    p.AbsolutePosition = rb.Vector2.new(0, 36)
    local host = frame(); host.Parent = p
    host.AbsoluteSize = rb.Vector2.new(100, 100); host.AbsolutePosition = rb.Vector2.new(10, 46)
    local s = Effects.shadow(p, t, { name = "DialogShadow", zIndex = 0 })
    Effects.follow(s, host, "dialog", t) -- initial sync runs when geometry already exists
    h.expect(s.Position.X.Offset).toBe(60); h.expect(s.Position.Y.Offset).toBe(70)
  end)
  h.it("gives its connections to the maid; after cleanup the signal no longer syncs", function()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    local s = Effects.shadow(p, t, { name = "DialogShadow", zIndex = 0 })
    local maid = R.Maid.new()
    Effects.follow(s, host, "dialog", t, maid)
    maid:DoCleanup()
    host.AbsoluteSize = rb.Vector2.new(200, 100); host.AbsolutePosition = rb.Vector2.new(0, 0)
    host:GetPropertyChangedSignal("AbsoluteSize"):Fire()
    host:GetPropertyChangedSignal("AbsolutePosition"):Fire()
    h.expect(s.Size).toBeNil()
  end)
end)

h.describe("effects.rim", function()
  h.it("adds exactly one UIGradient under the stroke with Rotation 90 and the dark edge alphas", function()
    local t, p = themed(), frame()
    local color = t.Colors.border
    local stroke = Create.stroke(color, 1); stroke.Parent = p
    local g = Effects.rim(stroke, t)
    h.expect(g.ClassName).toBe("UIGradient")
    h.expect(g.Parent).toBe(stroke)
    h.expect(g.Rotation).toBe(90)
    h.expect(g.Transparency.keypoints[1].Time).toBe(0)
    h.expect(g.Transparency.keypoints[1].Value).toBe(FX.dark.edgeTop)
    h.expect(g.Transparency.keypoints[2].Time).toBe(1)
    h.expect(g.Transparency.keypoints[2].Value).toBe(FX.dark.edgeBottom)
    h.expect(countClass(stroke, "UIGradient")).toBe(1)
    h.expect(countClass(p, "UIStroke")).toBe(1)
    h.expect(stroke.Color).toBe(color) -- never touched (compared by reference elsewhere)
  end)
  h.it("is idempotent: a second call updates the same gradient with the new mode's alphas", function()
    local t = themed()
    local stroke = Create.stroke(t.Colors.border, 1)
    local g1 = Effects.rim(stroke, t)
    Theme.applyMode(t, "light")
    local g2 = Effects.rim(stroke, t)
    h.expect(g2).toBe(g1)
    h.expect(countClass(stroke, "UIGradient")).toBe(1)
    h.expect(g2.Transparency.keypoints[1].Value).toBe(FX.light.edgeTop)
    h.expect(g2.Transparency.keypoints[2].Value).toBe(FX.light.edgeBottom)
  end)
  h.it("tolerates a nil stroke", function()
    h.expect(Effects.rim(nil, themed())).toBeNil()
  end)
end)

h.describe("effects.glow", function()
  h.it("tints the same asset with the token itself (identity), hidden, at the given ZIndex", function()
    desktop()
    local t, p = themed(), frame()
    local g = Effects.glow(p, t, t.Colors.primary, "control", 5)
    h.expect(g.ClassName).toBe("ImageLabel")
    h.expect(g.Name).toBe("Glow")
    h.expect(g.Parent).toBe(p)
    h.expect(g.Image).toBe(SHADOW)
    h.expect(g.ScaleType).toBe(rb.Enum.ScaleType.Slice)
    h.expect(g.ImageColor3).toBe(t.Colors.primary)
    h.expect(g.ImageTransparency).toBe(1)
    h.expect(g.ZIndex).toBe(5)
    h.expect(g.Active).toBe(false)
    h.expect(g.AnchorPoint.X).toBe(0.5)
    h.expect(Effects.glow(p, t, t.Colors.success, "control", 2, "ToggleGlow").Name).toBe("ToggleGlow")
  end)
  h.it("is nil on Mobile while controlGlow == 'auto', present when forced 'on', nil when 'off'", function()
    mobile()
    local ok, v = pcall(function()
      local p = frame()
      h.expect(Effects.glow(p, themed(), Theme.Colors.primary, "control", 1)).toBeNil()
      h.expect(Effects.glow(p, themed(nil, { controlGlow = "on" }), Theme.Colors.primary, "control", 1) ~= nil).toBeTruthy()
      h.expect(Effects.glow(p, themed(nil, { controlGlow = "off" }), Theme.Colors.primary, "control", 1)).toBeNil()
    end)
    desktop()
    if not ok then error(v, 0) end
    h.expect(Effects.glow(frame(), themed(), Theme.Colors.primary, "control", 1) ~= nil).toBeTruthy()
    h.expect(Effects.glow(frame(), themed(nil, { controlGlow = "off" }), Theme.Colors.primary, "control", 1)).toBeNil()
  end)
  h.it("is nil while shadowId is '' and throws without a colour token", function()
    desktop()
    h.expect(Effects.glow(frame(), Theme.new(), Theme.Colors.primary, "control", 1)).toBeNil()
    h.expect(function() Effects.glow(frame(), themed(), nil, "control", 1) end).toThrow("colorToken")
  end)
end)

h.describe("effects.lift", function()
  local function placed()
    local t, p = themed(), frame()
    local host = frame(); host.Parent = p
    host.AnchorPoint = rb.Vector2.new(0.5, 0.5)
    host.Position = rb.UDim2.new(0.5, 0, 0.5, 0); host.Size = rb.UDim2.new(0, 400, 0, 300)
    local s = Effects.shadow(p, t, { name = "WindowShadow", level = "window", zIndex = 0 })
    Effects.mirror(s, host, "window", t) -- rest 456 x 356
    return t, s, host
  end
  h.it("on: tweens Size +2*spreadDelta and alpha shadow+alphaDelta over Motion.fast; off: back to rest", function()
    local t, s = placed()
    h.mock.resetTweens()
    Effects.lift(s, t, true)
    local tw = h.mock.lastTween
    h.expect(tw.Instance).toBe(s)
    h.expect(tw.Info.Time).toBe(Theme.Motion.fast)
    h.expect(tw.Goal.Size.X.Offset).toBe(456 + 16); h.expect(tw.Goal.Size.Y.Offset).toBe(356 + 16)
    h.expect(tw.Goal.ImageTransparency).toBeCloseTo(FX.dark.shadow + Theme.Effect.lift.alphaDelta)
    Effects.lift(s, t, false)
    tw = h.mock.lastTween
    h.expect(tw.Goal.Size.X.Offset).toBe(456); h.expect(tw.Goal.Size.Y.Offset).toBe(356)
    h.expect(tw.Goal.ImageTransparency).toBe(FX.dark.shadow)
    h.expect(#h.mock.tweensFor(s)).toBe(2)
  end)
  h.it("mirror while lifted keeps the lift spread (drag calls mirror every frame)", function()
    local t, s, host = placed()
    Effects.lift(s, t, true)
    host.Size = rb.UDim2.new(0, 500, 0, 300)
    Effects.mirror(s, host, "window", t)
    h.expect(s.Size.X.Offset).toBe(556 + 16); h.expect(s.Size.Y.Offset).toBe(356 + 16)
    Effects.lift(s, t, false)
    h.expect(s.Size.X.Offset).toBe(556); h.expect(s.Size.Y.Offset).toBe(356)
  end)
  h.it("a shadow lifted before any placement grows from its current Size and returns to it", function()
    local t = themed()
    local s = Effects.shadow(frame(), t, { name = "S", zIndex = 0 })
    s.Size = rb.UDim2.new(0, 100, 0, 40)
    Effects.lift(s, t, true)
    h.expect(s.Size.X.Offset).toBe(116); h.expect(s.Size.Y.Offset).toBe(56)
    Effects.lift(s, t, false)
    h.expect(s.Size.X.Offset).toBe(100); h.expect(s.Size.Y.Offset).toBe(40)
  end)
  h.it("applies instantly with no tween under reduced motion", function()
    h.withReducedMotion(R, function()
      local t, s = placed()
      h.mock.resetTweens()
      Effects.lift(s, t, true)
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(s.Size.X.Offset).toBe(456 + 16)
      h.expect(s.ImageTransparency).toBeCloseTo(FX.dark.shadow + Theme.Effect.lift.alphaDelta)
    end)
  end)
end)

h.describe("effects.reskin", function()
  h.it("shadow: re-applies the mode alpha, keeping the lift delta while lifted", function()
    local t = themed()
    local s = Effects.shadow(frame(), t, { name = "S", zIndex = 0 })
    Theme.applyMode(t, "light")
    Effects.reskin(s, t, "shadow")
    h.expect(s.ImageTransparency).toBe(FX.light.shadow)
    Effects.lift(s, t, true)
    Theme.applyMode(t, "dark")
    Effects.reskin(s, t) -- kind remembered from creation
    h.expect(s.ImageTransparency).toBeCloseTo(FX.dark.shadow + Theme.Effect.lift.alphaDelta)
  end)
  h.it("glow: swaps the tint token by identity; a hidden glow stays hidden, a shown one takes the mode alpha", function()
    desktop()
    local t = themed()
    local g = Effects.glow(frame(), t, t.Colors.primary, "control", 1)
    local accent = rb.Color3.fromRGB(59, 130, 246)
    Effects.reskin(g, t, "glow", accent)
    h.expect(g.ImageColor3).toBe(accent)
    h.expect(g.ImageTransparency).toBe(1)
    g.ImageTransparency = FX.dark.glow
    Theme.applyMode(t, "light")
    Effects.reskin(g, t, "glow")
    h.expect(g.ImageColor3).toBe(accent) -- token remembered from the previous reskin
    h.expect(g.ImageTransparency).toBe(FX.light.glow)
  end)
  h.it("rim: accepts the stroke or its gradient and never adds a second gradient", function()
    local t = themed()
    local stroke = Create.stroke(t.Colors.border, 1)
    local g = Effects.rim(stroke, t)
    Theme.applyMode(t, "light")
    Effects.reskin(stroke, t, "rim")
    h.expect(g.Transparency.keypoints[2].Value).toBe(FX.light.edgeBottom)
    Theme.applyMode(t, "dark")
    Effects.reskin(g, t, "rim")
    h.expect(g.Transparency.keypoints[2].Value).toBe(FX.dark.edgeBottom)
    h.expect(countClass(stroke, "UIGradient")).toBe(1)
  end)
  h.it("throws on an unknown kind", function()
    h.expect(function() Effects.reskin(frame(), themed(), "halo") end).toThrow("kind")
  end)
end)

h.describe("effects.skeleton", function()
  h.it("builds a surface block with a corner and one looping Linear shimmer gradient", function()
    local t, p = Theme.new(), frame()
    h.mock.resetTweens()
    local sk = Effects.skeleton(p, t, { size = rb.UDim2.new(1, 0, 0, 20), radius = 4 })
    local f = sk.Frame
    h.expect(f.ClassName).toBe("Frame")
    h.expect(f.Parent).toBe(p)
    h.expect(f.BackgroundColor3).toBe(t.Colors.surface)
    h.expect(f.Size.Y.Offset).toBe(20)
    h.expect(f:FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(4)
    local g = f:FindFirstChildOfClass("UIGradient")
    h.expect(g).toBe(sk.Gradient)
    h.expect(g.Rotation).toBe(15)
    h.expect(g.Color.color[1].Value.R).toBe(1)
    h.expect(g.Color.color[2].Value).toBe(FX.dark.inset)
    h.expect(g.Color.color[3].Value.R).toBe(1)
    local tws = h.mock.tweensFor(g)
    h.expect(#tws).toBe(1)
    h.expect(tws[1].Info.RepeatCount).toBe(-1)
    h.expect(tws[1].Info.Reverses).toBe(false)
    h.expect(tws[1].Info.EasingStyle.Name).toBe("Linear")
    h.expect(tws[1].Info.Time).toBe(1.1)
    h.expect(tws[1].Goal.Offset.X).toBe(1); h.expect(tws[1].Goal.Offset.Y).toBe(0)
  end)
  h.it("Stop cancels the loop, fades the block out and destroys it (idempotent)", function()
    local t, p = Theme.new(), frame()
    h.mock.resetTweens()
    local sk = Effects.skeleton(p, t, { size = rb.UDim2.new(1, 0, 0, 20) })
    local loopTw = h.mock.tweensFor(sk.Gradient)[1]
    sk.Stop()
    h.expect(loopTw.cancelled).toBe(true)
    local fade = h.mock.lastTween
    h.expect(fade.Instance).toBe(sk.Frame)
    h.expect(fade.Goal.BackgroundTransparency).toBe(1)
    h.expect(fade.Info.Time).toBe(Theme.Motion.exit)
    h.expect(sk.Frame.Parent).toBeNil()
    h.expect(p:FindFirstChild("Skeleton")).toBeNil()
    local n = h.mock.tweenCount()
    sk.Stop()
    h.expect(h.mock.tweenCount()).toBe(n)
  end)
  h.it("honours the light inset band, opts.band and an Effect.skeleton token group when present", function()
    local light = Theme.applyMode(Theme.new(), "light")
    h.expect(Effects.skeleton(frame(), light, {}).Gradient.Color.color[2].Value).toBe(FX.light.inset)
    local band = rb.Color3.fromRGB(1, 2, 3)
    h.expect(Effects.skeleton(frame(), light, { band = band }).Gradient.Color.color[2].Value).toBe(band)
    local t = Theme.new({ Effect = { skeleton = { period = 2, rotation = 30 } } })
    h.mock.resetTweens()
    local sk = Effects.skeleton(frame(), t, {})
    h.expect(sk.Gradient.Rotation).toBe(30)
    h.expect(h.mock.lastTween.Info.Time).toBe(2)
  end)
  h.it("is a static block under reduced motion: no tween, Stop destroys immediately", function()
    h.withReducedMotion(R, function()
      local p = frame()
      h.mock.resetTweens()
      local sk = Effects.skeleton(p, Theme.new(), { size = rb.UDim2.new(1, 0, 0, 20) })
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(sk.Frame.Parent).toBe(p)
      sk.Stop()
      h.expect(h.mock.tweenCount()).toBe(0)
      h.expect(sk.Frame.Parent).toBeNil()
    end)
  end)
end)

h.run()
