local h = require("tests.helper")
local R = h.loadLib(); local Keybind, Create, Config = R.Keybind, R.Create, R.Config
h.describe("keybind", function()
  h.it("default key persists by name and restores", function()
    local cfg = Config.new({ FileName = "KB", AutoSave = false })
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Panic", Default = h.roblox.Enum.KeyCode.P, Flag = "panic", Config = cfg })
    h.expect(k.GetKey().Name).toBe("P")
    h.expect(cfg:Get("panic")).toBe("P")
  end)
  h.it("accepts a string-name default (not just an EnumItem)", function()
    local k = Keybind.new({ Text = "X", Default = "P" })
    h.expect(k.GetKey().Name).toBe("P")
  end)
  h.it("fires Callback when bound key pressed", function()
    local fired = 0
    local k = Keybind.new({ Text = "Go", Default = h.roblox.Enum.KeyCode.E, Callback = function() fired = fired + 1 end })
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(fired).toBe(1)
  end)
  h.it("fires OnChanged with the new key when rebound (and not on a normal press)", function()
    local got, changes = nil, 0
    local k = Keybind.new({ Text = "Toggle", Default = h.roblox.Enum.KeyCode.RightControl,
      OnChanged = function(key) got = key; changes = changes + 1 end })
    local uis = h.roblox.game:GetService("UserInputService")
    -- pressing the bound key must NOT count as a change
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.RightControl, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(changes).toBe(0)
    -- click to listen, then press a new key -> rebind fires OnChanged with that key
    k.Frame.MouseButton1Click:Fire()
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.LeftAlt, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(changes).toBe(1)
    h.expect(got.Name).toBe("LeftAlt")
    h.expect(k.GetKey().Name).toBe("LeftAlt")
  end)
  h.it("fires OnChanged from SetKey too", function()
    local got
    local k = Keybind.new({ Text = "T", Default = "P", OnChanged = function(key) got = key end })
    k.SetKey(h.roblox.Enum.KeyCode.LeftAlt)
    h.expect(got.Name).toBe("LeftAlt")
  end)
  h.it("chip stroke shows the ring at focusThickness while listening and returns to border/1 on capture (1.7)", function()
    local closure
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P",
      AccentReg = function(fn) closure = fn; return function() end end })
    local chip = k.Frame:FindFirstChild("Key")
    local strokes = 0
    for _, c in ipairs(chip:GetChildren()) do if c.ClassName == "UIStroke" then strokes = strokes + 1 end end
    h.expect(strokes).toBe(1)                          -- exactly one stroke on the chip
    local stroke = chip:FindFirstChildOfClass("UIStroke")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    k.Frame.MouseButton1Click:Fire()                   -- listening
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
    h.expect(h.mock.lastTween.Info.Time).toBe(R.Theme.Motion.fast)
    closure("mode")                                    -- reskin while listening keeps the ring
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(k.GetKey().Name).toBe("E")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    closure("mode")                                    -- and stays at border once idle
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
  end)
  h.it("listening ring lands instantly under reduced motion", function()
    h.withReducedMotion(R, function()
      local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
      local stroke = k.Frame:FindFirstChild("Key"):FindFirstChildOfClass("UIStroke")
      h.mock.resetTweens()
      k.Frame.MouseButton1Click:Fire()
      h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
      h.expect(h.mock.tweenCount()).toBe(0)
    end)
  end)
  h.it("text parts carry their theme Font roles (1.2)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Description = "d", Default = "P" })
    local label = k.Frame:FindFirstChild("Label")
    h.expect(label.TextSize).toBe(R.Theme.Font.label.Size)
    h.expect(label.FontFace.Weight).toBe(R.Theme.Font.label.Weight)
    h.expect(k.Frame:FindFirstChild("Description").TextSize).toBe(R.Theme.Font.muted.Size)
    h.expect(k.Frame:FindFirstChild("Key").TextSize).toBe(R.Theme.Font.muted.Size)
  end)
end)
h.run()
