local h = require("tests.helper")
local R = h.loadLib(); local Keybind, Create, Config = R.Keybind, R.Create, R.Config
h.describe("keybind", function()
  h.it("default key persists by name and restores", function()
    local cfg = Config.new({ FileName = "KB", AutoSave = false })
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Panic", Default = h.roblox.Enum.KeyCode.P, Flag = "panic", Config = cfg })
    h.expect(k.GetKey().Name).toBe("P")
    h.expect(cfg:Get("panic")).toBe("P")
  end)
  h.it("accepts a string-name default (not just an EnumItem)", function()
    local k = Keybind.new({ Text = "X", Default = "P" })
    h.expect(k.GetKey().Name).toBe("P")
  end)
  h.it("fires Callback when bound key pressed", function()
    local fired = 0
    local k = Keybind.new({ Text = "Go", Default = h.roblox.Enum.KeyCode.E, Callback = function() fired = fired + 1 end })
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(fired).toBe(1)
  end)
  h.it("fires OnChanged with the new key when rebound (and not on a normal press)", function()
    local got, changes = nil, 0
    local k = Keybind.new({ Text = "Toggle", Default = h.roblox.Enum.KeyCode.RightControl,
      OnChanged = function(key) got = key; changes = changes + 1 end })
    local uis = h.roblox.game:GetService("UserInputService")
    -- pressing the bound key must NOT count as a change
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.RightControl, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(changes).toBe(0)
    -- click to listen, then press a new key -> rebind fires OnChanged with that key
    k.Frame.MouseButton1Click:Fire()
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.LeftAlt, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(changes).toBe(1)
    h.expect(got.Name).toBe("LeftAlt")
    h.expect(k.GetKey().Name).toBe("LeftAlt")
  end)
  h.it("fires OnChanged from SetKey too", function()
    local got
    local k = Keybind.new({ Text = "T", Default = "P", OnChanged = function(key) got = key end })
    k.SetKey(h.roblox.Enum.KeyCode.LeftAlt)
    h.expect(got.Name).toBe("LeftAlt")
  end)
  h.it("chip stroke shows the ring at focusThickness while listening and returns to border/1 on capture (1.7)", function()
    local closure
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P",
      AccentReg = function(fn) closure = fn; return function() end end })
    local chip = k.Frame:FindFirstChild("Key")
    local strokes = 0
    for _, c in ipairs(chip:GetChildren()) do if c.ClassName == "UIStroke" then strokes = strokes + 1 end end
    h.expect(strokes).toBe(1)                          -- exactly one stroke on the chip
    local stroke = chip:FindFirstChildOfClass("UIStroke")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    k.Frame.MouseButton1Click:Fire()                   -- listening
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
    h.expect(h.mock.lastTween.Info.Time).toBe(R.Theme.Motion.fast)
    closure("mode")                                    -- reskin while listening keeps the ring
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(k.GetKey().Name).toBe("E")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    closure("mode")                                    -- and stays at border once idle
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
  end)
  h.it("listening ring lands instantly under reduced motion", function()
    h.withReducedMotion(R, function()
      local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
      local stroke = k.Frame:FindFirstChild("Key"):FindFirstChildOfClass("UIStroke")
      h.mock.resetTweens()
      k.Frame.MouseButton1Click:Fire()
      h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
      h.expect(h.mock.tweenCount()).toBe(0)
    end)
  end)
  h.it("text parts carry their theme Font roles (1.2)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Description = "d", Default = "P" })
    local label = k.Frame:FindFirstChild("Label")
    h.expect(label.TextSize).toBe(R.Theme.Font.label.Size)
    h.expect(label.FontFace.Weight).toBe(R.Theme.Font.label.Weight)
    h.expect(k.Frame:FindFirstChild("Description").TextSize).toBe(R.Theme.Font.muted.Size)
    h.expect(k.Frame:FindFirstChild("Key").TextSize).toBe(R.Theme.Font.muted.Size)
  end)
  -- ---- visual-polish phase 2 (2.16 kbd chip + listening, 2.7 row, 2.8 disabled) ----
  h.it("the chip is kbd-style: background fill, auto width, anchored to the row's right edge (2.16)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local chip = k.Frame:FindFirstChild("Key")
    h.expect(chip.BackgroundColor3).toBe(R.Theme.Colors.background)
    h.expect(chip.AutomaticSize).toBe(h.roblox.Enum.AutomaticSize.X)
    h.expect(chip.AnchorPoint.X).toBe(1)                -- grows leftwards, never past the row edge
    h.expect(chip.AnchorPoint.Y).toBe(0.5)
    h.expect(chip.Position.X.Scale).toBe(1)
    h.expect(chip.Position.X.Offset).toBe(0)
    h.expect(chip.Size.Y.Offset).toBe(R.Theme.Sizes.chip)
    h.expect(chip:FindFirstChildOfClass("UISizeConstraint").MinSize.X).toBe(R.Theme.Sizes.touchHit)
    h.expect(chip:FindFirstChildOfClass("UIPadding").PaddingLeft.Offset).toBe(R.Theme.Spacing.gap)
    h.expect(chip:FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
  end)
  h.it("listening shows a muted prompt and pulses the stroke until capture (2.16)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local chip = k.Frame:FindFirstChild("Key")
    local stroke = chip:FindFirstChildOfClass("UIStroke")
    h.expect(chip.Text).toBe("P")
    h.mock.resetTweens()
    k.Frame.MouseButton1Click:Fire()
    h.expect(chip.Text).toBe("Press a key")
    h.expect(chip.TextColor3).toBe(R.Theme.Colors.mutedForeground)
    local loop
    for _, tw in ipairs(h.mock.tweensFor(stroke)) do if tw.Info.RepeatCount == -1 then loop = tw end end
    h.expect(loop ~= nil).toBeTruthy()                  -- an endless ping-pong on the stroke alpha
    h.expect(loop.Info.Reverses).toBe(true)
    h.expect(loop.Info.EasingStyle).toBe(h.roblox.Enum.EasingStyle.Sine)
    h.expect(loop.Goal.Transparency ~= nil).toBeTruthy()
    h.expect(loop.cancelled).toBe(false)
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(loop.cancelled).toBe(true)                 -- capture stops the pulse
    h.expect(stroke.Transparency).toBe(R.Theme.Stroke.control)
    h.expect(chip.Text).toBe("E")
    h.expect(chip.TextColor3).toBe(R.Theme.Colors.foreground)
    h.expect(chip:FindFirstChildOfClass("UIScale").Scale).toBe(1)   -- popped, then settled at rest
  end)
  h.it("the capture flash is played BEFORE the ring tween that restores the chip (2.16)", function()
    -- Roblox cancels an older tween WHOLE when a newer one on the same instance shares a
    -- property, so the focus recipe's { Thickness, Color } tween has to be the LAST writer on the
    -- chip stroke -- otherwise the flash's Color tween would cancel it and strand the chip at
    -- Stroke.focusThickness for good. The mock lands every goal inside Play(), so the final
    -- Thickness alone can never catch this: only the ORDER of the two tweens can.
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local stroke = k.Frame:FindFirstChild("Key"):FindFirstChildOfClass("UIStroke")
    k.Frame.MouseButton1Click:Fire()                    -- listening (the pulse loop starts here)
    h.mock.resetTweens()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    local played = h.mock.tweensFor(stroke)
    h.expect(#played).toBe(2)                           -- the accent flash, then the ring restore
    h.expect(played[1].Goal.Thickness == nil).toBeTruthy()          -- flash: colour/alpha only
    h.expect(played[1].Goal.Color).toBe(R.Theme.Colors.border)
    h.expect(played[2].Goal.Thickness).toBe(1)                      -- ring restore wins the race
    h.expect(played[2].Info.Time).toBe(R.Theme.Motion.fast)
    h.expect(played[2].cancelled).toBe(false)
    h.expect(stroke.Thickness).toBe(1)
  end)
  h.it("Escape cancels listening and keeps the current binding (2.16)", function()
    local fired, changes = 0, 0
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P",
      Callback = function() fired = fired + 1 end, OnChanged = function() changes = changes + 1 end })
    local chip = k.Frame:FindFirstChild("Key")
    local stroke = chip:FindFirstChildOfClass("UIStroke")
    local uis = h.roblox.game:GetService("UserInputService")
    k.Frame.MouseButton1Click:Fire()
    h.expect(chip.Text).toBe("Press a key")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.Escape, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(k.GetKey().Name).toBe("P")
    h.expect(chip.Text).toBe("P")
    h.expect(changes).toBe(0)
    h.expect(stroke.Thickness).toBe(1)
    -- listening really ended: the old binding fires again instead of being rebound
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.P, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(fired).toBe(1)
    h.expect(k.GetKey().Name).toBe("P")
  end)
  h.it("an InputBegan with no KeyCode is captured, never read as Escape (2.16)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local uis = h.roblox.game:GetService("UserInputService")
    k.Frame.MouseButton1Click:Fire()
    uis.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(k.GetKey().Name).toBe("Unknown")           -- nil == nil must not cancel a capture
    h.expect(k.Frame:FindFirstChild("Key").Text).toBe("Unknown")
  end)
  h.it("the row answers hover with a wash and press with a chip dip (2.7)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local wash = k.Frame:FindFirstChild("Hover")
    local chip = k.Frame:FindFirstChild("Key")
    h.expect(wash ~= nil).toBeTruthy()
    h.expect(wash.ZIndex).toBe(0)                       -- above the row fill, below label and chip
    h.expect(wash.Position.X.Offset).toBe(-R.Theme.Spacing.inputX)  -- cancels the row's UIPadding
    h.expect(wash.BackgroundTransparency).toBe(1)
    k.Frame.MouseEnter:Fire()
    h.expect(wash.BackgroundTransparency).toBe(R.Theme.Opacity.hoverWash)
    k.Frame.MouseButton1Down:Fire()
    h.expect(wash.BackgroundTransparency).toBe(R.Theme.Opacity.pressWash)
    h.expect(chip:FindFirstChildOfClass("UIScale").Scale).toBe(R.Theme.Motion.pressScale)
    k.Frame.MouseButton1Up:Fire()
    h.expect(chip:FindFirstChildOfClass("UIScale").Scale).toBe(1)
    k.Frame.MouseLeave:Fire()
    h.expect(wash.BackgroundTransparency).toBe(1)
  end)
  h.it("SetEnabled(false) dims the chip and refuses to arm listening (2.8)", function()
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Bind", Default = "P" })
    local chip = k.Frame:FindFirstChild("Key")
    k.SetEnabled(false)
    h.expect(chip.BackgroundTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(chip.TextTransparency).toBe(R.Theme.Opacity.disabled)
    k.Frame.MouseButton1Click:Fire()
    h.expect(chip.Text).toBe("P")                       -- never armed
    k.SetEnabled(true)
    h.expect(chip.BackgroundTransparency).toBe(0)
    h.expect(chip.TextTransparency).toBe(0)
    k.Frame.MouseButton1Click:Fire()
    h.expect(chip.Text).toBe("Press a key")
    k.SetEnabled(false)                                 -- disabling mid-listen disarms it
    h.expect(chip.Text).toBe("P")
    h.expect(chip:FindFirstChildOfClass("UIStroke").Thickness).toBe(1)
  end)
end)
h.run()
