local h = require("tests.helper")
local mockmod = require("tests.mock_roblox")
local Enum = h.roblox.Enum
local Instance = h.roblox.Instance

-- strict-mode toggle scoped to one test (verify_bundle runs the whole mock strict)
local function withStrict(fn)
  mockmod.strict = true
  local ok, err = pcall(fn)
  mockmod.strict = false
  if not ok then error(err, 0) end
end

h.describe("mock device surface", function()
  h.it("exposes GuiService, UserInputService capabilities, and a camera", function()
    local gui = h.roblox.game:GetService("GuiService")
    h.expect(type(gui.IsTenFootInterface)).toBe("function")
    h.mock.tenFoot = true
    h.expect(gui:IsTenFootInterface()).toBe(true)
    h.mock.tenFoot = false
    h.expect(gui:IsTenFootInterface()).toBe(false)

    local uis = h.roblox.game:GetService("UserInputService")
    h.expect(uis.MouseEnabled).toBe(true)
    h.expect(type(uis.GetLastInputType)).toBe("function")
    h.expect(type(uis.GetPropertyChangedSignal)).toBe("function")
    h.expect(uis.LastInputTypeChanged ~= nil).toBeTruthy()
    h.expect(uis:GetLastInputType()).toBe(h.roblox.Enum.UserInputType.Keyboard)
    local sig = uis:GetPropertyChangedSignal("TouchEnabled")
    h.expect(sig ~= nil).toBeTruthy()

    local cam = h.roblox.workspace.CurrentCamera
    h.expect(cam.ViewportSize.X).toBe(1280)
    h.expect(cam.ViewportSize.Y).toBe(720)
    h.expect(h.roblox.Enum.UserInputType.Gamepad1.Name).toBe("Gamepad1")
  end)
end)

h.describe("mock TweenInfo", function()
  h.it("captures all six args with Roblox defaults", function()
    local TI = h.roblox.TweenInfo
    local i3 = TI.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
    h.expect(i3.Time).toBe(0.2)
    h.expect(i3.RepeatCount).toBe(0); h.expect(i3.Reverses).toBe(false); h.expect(i3.DelayTime).toBe(0)
    local loop = TI.new(0.8, Enum.EasingStyle.Linear, Enum.EasingDirection.InOut, -1)
    h.expect(loop.RepeatCount).toBe(-1)
    local full = TI.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.In, 2, true, 0.1)
    h.expect(full.RepeatCount).toBe(2); h.expect(full.Reverses).toBe(true); h.expect(full.DelayTime).toBe(0.1)
    local d = TI.new()
    h.expect(d.Time).toBe(1)
    h.expect(d.EasingStyle).toBe(Enum.EasingStyle.Quad)
    h.expect(d.EasingDirection).toBe(Enum.EasingDirection.Out)
  end)
  h.it("strict mode rejects nil numeric slots like Roblox but tolerates a trailing nil style", function()
    local TI = h.roblox.TweenInfo
    withStrict(function()
      h.expect(function() TI.new(nil) end).toThrow("invalid argument #1 to 'new' (number expected, got nil)")
      h.expect(function() TI.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 0, false, nil) end)
        .toThrow("invalid argument #6 to 'new' (number expected, got nil)")
      h.expect(function() TI.new(0.2, nil, Enum.EasingDirection.Out) end).toThrow("#2")
      h.expect(function() TI.new(0.2, Enum.EasingStyle.Quad, nil, 0) end).toThrow("#3")
      h.expect(function() TI.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, "x") end).toThrow("#4")
      h.expect(function() TI.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 0, nil, 0.1) end).toThrow("#5")
      h.expect(TI.new(0.2, nil).Time).toBe(0.2)
      h.expect(TI.new(0.8, Enum.EasingStyle.Linear, Enum.EasingDirection.InOut, -1).RepeatCount).toBe(-1)
      h.expect(TI.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 0, false, 0.05).DelayTime).toBe(0.05)
    end)
    h.expect(TI.new(nil).Time).toBe(1) -- lenient mode keeps today's forgiveness
  end)
end)

h.describe("mock TweenService capture", function()
  h.it("records every Create in mock.tweens with per-instance lookup", function()
    local TS = h.roblox.game:GetService("TweenService")
    h.mock.resetTweens()
    local a, b = Instance.new("Frame"), Instance.new("Frame")
    TS:Create(a, h.roblox.TweenInfo.new(0.1), { Rotation = 10 })
    local t2 = TS:Create(b, h.roblox.TweenInfo.new(0.1), { Rotation = 20 })
    local t3 = TS:Create(a, h.roblox.TweenInfo.new(0.1), { Rotation = 30 })
    h.expect(h.mock.tweenCount()).toBe(3)
    h.expect(h.mock.lastTween).toBe(t3)
    h.expect(h.mock.tweensFor(a)).toHaveLength(2)
    h.expect(h.mock.tweensFor(b)[1]).toBe(t2)
    h.mock.resetTweens()
    h.expect(h.mock.tweenCount()).toBe(0)
    h.expect(h.mock.lastTween).toBeNil()
  end)
  h.it("Play is synchronous even for RepeatCount -1; Cancel/Pause only set flags", function()
    local TS = h.roblox.game:GetService("TweenService")
    local f = Instance.new("ImageLabel")
    local tw = TS:Create(f, h.roblox.TweenInfo.new(0.8, Enum.EasingStyle.Linear, Enum.EasingDirection.InOut, -1),
      { Rotation = 360 })
    local fired, state = 0, nil
    tw.Completed:Connect(function(s) fired = fired + 1; state = s end)
    h.expect(tw.PlaybackState).toBe(Enum.PlaybackState.Begin)
    tw:Play()
    h.expect(f.Rotation).toBe(360)
    h.expect(fired).toBe(1)
    h.expect(state).toBe(Enum.PlaybackState.Completed)
    h.expect(tw.played).toBeTruthy()
    h.expect(tw.cancelled).toBe(false)
    h.expect(tw.paused).toBe(false)
    tw:Pause(); h.expect(tw.paused).toBe(true); h.expect(tw.PlaybackState).toBe(Enum.PlaybackState.Paused)
    tw:Cancel(); h.expect(tw.cancelled).toBe(true); h.expect(tw.PlaybackState).toBe(Enum.PlaybackState.Cancelled)
    h.expect(fired).toBe(1) -- Cancel after a finished tween does not re-fire Completed
  end)
end)

h.describe("mock datatypes and enums", function()
  h.it("adds easing styles, stroke/playback enums and dialog keycodes", function()
    for _, n in ipairs({ "Quad", "Cubic", "Exponential", "Elastic", "Bounce", "Circular", "Quart", "Back" }) do
      h.expect(Enum.EasingStyle[n].Name).toBe(n)
    end
    h.expect(Enum.ApplyStrokeMode.Border.Name).toBe("Border")
    h.expect(Enum.ApplyStrokeMode.Contextual.Name).toBe("Contextual")
    h.expect(Enum.PlaybackState.Completed.Name).toBe("Completed")
    h.expect(Enum.LineJoinMode.Round.Name).toBe("Round")
    for _, n in ipairs({ "Escape", "Return", "ButtonA", "ButtonB", "E" }) do h.expect(Enum.KeyCode[n].Name).toBe(n) end
  end)
  h.it("Rect.new, Font.fromName and TextService:GetTextSize", function()
    local r = h.roblox.Rect.new(1, 2, 3, 4)
    h.expect(r.Min.X).toBe(1); h.expect(r.Min.Y).toBe(2); h.expect(r.Max.X).toBe(3); h.expect(r.Max.Y).toBe(4)
    local f = h.roblox.Font.fromName("BuilderSans")
    h.expect(f.Family).toBe("BuilderSans"); h.expect(f.Weight).toBe(Enum.FontWeight.Regular); h.expect(f.Style).toBeNil()
    local fb = h.roblox.Font.fromName("BuilderSans", Enum.FontWeight.Bold, Enum.FontStyle.Italic)
    h.expect(fb.Weight).toBe(Enum.FontWeight.Bold); h.expect(fb.Style).toBe(Enum.FontStyle.Italic)
    local ts = h.roblox.game:GetService("TextService")
    local sz = ts:GetTextSize("hello", 14, f, h.roblox.Vector2.new(1000, 100))
    h.expect(sz.X).toBeCloseTo(5 * 14 * 0.55)
    h.expect(sz.Y).toBe(14)
  end)
end)

h.describe("mock images", function()
  h.it("imagesLoaded=false seeds IsLoaded=false on new images only; nil keeps IsLoaded unset", function()
    h.expect(Instance.new("ImageLabel").IsLoaded).toBeNil()
    h.mock.imagesLoaded = false
    local img, btn, fr = Instance.new("ImageLabel"), Instance.new("ImageButton"), Instance.new("Frame")
    h.mock.imagesLoaded = nil
    h.expect(img.IsLoaded).toBe(false); h.expect(btn.IsLoaded).toBe(false); h.expect(fr.IsLoaded).toBeNil()
    -- property signals never auto-fire: the test flips the prop and fires it explicitly
    local seen = 0
    img:GetPropertyChangedSignal("IsLoaded"):Connect(function() seen = seen + 1 end)
    img.IsLoaded = true
    h.expect(seen).toBe(0)
    img:GetPropertyChangedSignal("IsLoaded"):Fire()
    h.expect(seen).toBe(1)
    h.expect(img:GetPropertyChangedSignal("IsLoaded")).toBe(img:GetPropertyChangedSignal("IsLoaded")) -- cached per (inst, prop)
  end)
end)

h.describe("mock timers", function()
  h.it("immediate mode runs task.delay synchronously; task.cancel is a no-op", function()
    h.expect(h.mock.timerMode).toBe("immediate")
    local ran
    local th = h.roblox.task.delay(5, function(a, b) ran = a + b end, 1, 2)
    h.expect(ran).toBe(3)
    h.expect(type(th)).toBe("thread")
    h.roblox.task.cancel(th)
    h.expect(h.mock.timerCount()).toBe(0)
  end)
  h.it("queued mode parks callbacks until mock.advance reaches their due time, in (due, insertion) order", function()
    local log = {}
    h.withQueuedTimers(function()
      local task = h.roblox.task
      task.delay(0.3, function() log[#log + 1] = "c" end)
      task.delay(0.1, function(x) log[#log + 1] = x end, "a")
      task.delay(0.1, function() log[#log + 1] = "b" end)
      local dead = task.delay(0.2, function() log[#log + 1] = "cancelled" end)
      h.expect(#log).toBe(0)
      h.expect(h.mock.timerCount()).toBe(4)
      task.cancel(dead)
      h.expect(h.mock.timerCount()).toBe(3)
      h.mock.advance(0.1)
      h.expect(table.concat(log, ",")).toBe("a,b")
      h.mock.advance(0.1) -- t=0.2: only the cancelled entry was due
      h.expect(table.concat(log, ",")).toBe("a,b")
      -- a callback may queue a follow-up; it runs in the same advance once due (after earlier-queued peers)
      task.delay(0.05, function() task.delay(0, function() log[#log + 1] = "nested" end) end)
      h.mock.advance(0.1)
      h.expect(table.concat(log, ",")).toBe("a,b,c,nested")
      h.expect(h.mock.timerCount()).toBe(0)
      h.expect(h.roblox.tick()).toBeCloseTo(0.3)
    end)
    h.expect(h.mock.timerMode).toBe("immediate")
    h.expect(#h.mock.timers).toBe(0)
  end)
  h.it("withQueuedTimers restores immediate mode and clears the queue when fn throws", function()
    h.expect(function()
      h.withQueuedTimers(function() h.roblox.task.delay(1, function() end); error("boom") end)
    end).toThrow("boom")
    h.expect(h.mock.timerMode).toBe("immediate")
    h.expect(#h.mock.timers).toBe(0)
  end)
end)

h.describe("mock Destroy", function()
  h.it("tears down the whole subtree, firing Destroying on each descendant once", function()
    local root, child, grand = Instance.new("Frame"), Instance.new("Frame"), Instance.new("TextLabel")
    child.Parent = root; grand.Parent = child
    local fired = {}
    child.Destroying:Connect(function() fired[#fired + 1] = "child" end)
    grand.Destroying:Connect(function() fired[#fired + 1] = "grand" end)
    root:Destroy()
    h.expect(root:GetChildren()).toHaveLength(0)
    h.expect(child:GetChildren()).toHaveLength(0)
    h.expect(child.Parent).toBeNil()
    h.expect(grand.Parent).toBeNil()
    h.expect(root._destroyed).toBe(true); h.expect(child._destroyed).toBe(true); h.expect(grand._destroyed).toBe(true)
    h.expect(table.concat(fired, ",")).toBe("child,grand")
    root:Destroy() -- second Destroy is a no-op, like Roblox
    h.expect(#fired).toBe(2)
  end)
  h.it("detaches the destroyed instance from its parent", function()
    local p, c = Instance.new("Frame"), Instance.new("Frame")
    c.Name = "C"; c.Parent = p
    c:Destroy()
    h.expect(p:FindFirstChild("C")).toBeNil()
    h.expect(p:GetChildren()).toHaveLength(0)
    h.expect(c.Parent).toBeNil()
  end)
end)

h.describe("mock events and services", function()
  h.it("exposes selection/destroying/mouse-moved events; unknown members read nil", function()
    local f = Instance.new("Frame")
    for _, ev in ipairs({ "SelectionGained", "SelectionLost", "Destroying", "MouseMoved", "MouseEnter" }) do
      local n = 0
      f[ev]:Connect(function() n = n + 1 end)
      f[ev]:Fire()
      h.expect(n).toBe(1)
    end
    h.expect(f.NotAnEvent).toBeNil()
  end)
  h.it("GuiService.ReducedMotionEnabled defaults false with a cached property signal", function()
    local gs = h.roblox.game:GetService("GuiService")
    h.expect(gs.ReducedMotionEnabled).toBe(false)
    local sig = gs:GetPropertyChangedSignal("ReducedMotionEnabled")
    h.expect(sig).toBe(gs:GetPropertyChangedSignal("ReducedMotionEnabled"))
    local seen
    sig:Connect(function() seen = gs.ReducedMotionEnabled end)
    gs.ReducedMotionEnabled = true; sig:Fire()
    h.expect(seen).toBe(true)
    gs.ReducedMotionEnabled = false
  end)
  h.it("heartbeatHandlers counts live Heartbeat connections", function()
    local base = h.mock.heartbeatHandlers()
    local rs = h.roblox.game:GetService("RunService")
    local c = rs.Heartbeat:Connect(function() end)
    h.expect(h.mock.heartbeatHandlers()).toBe(base + 1)
    c:Disconnect()
    h.expect(h.mock.heartbeatHandlers()).toBe(base)
    rs.Heartbeat:Once(function() end)
    h.expect(h.mock.heartbeatHandlers()).toBe(base + 1)
    h.mock.stepHeartbeat(0.016)
    h.expect(h.mock.heartbeatHandlers()).toBe(base)
  end)
end)

h.describe("mock strict allowlist", function()
  local function ok(cls, prop, v) local i = Instance.new(cls); i[prop] = v; h.expect(i[prop]).toBe(v) end
  local function rejects(cls, prop)
    h.expect(function() Instance.new(cls)[prop] = 1 end).toThrow(prop .. " is not a valid member of " .. cls)
  end
  h.it("shared properties stay valid on every owning class", function()
    withStrict(function()
      ok("Frame", "Rotation", 5); ok("ImageLabel", "Rotation", 5); ok("UIGradient", "Rotation", 90)
      rejects("UIStroke", "Rotation"); rejects("ScreenGui", "Rotation")
      ok("UIStroke", "Color", 1); ok("UIGradient", "Color", 1); rejects("Frame", "Color")
      ok("UIStroke", "Transparency", 0.3); ok("UIGradient", "Transparency", 1); rejects("ImageLabel", "Transparency")
      ok("UIGradient", "Offset", 1); rejects("Frame", "Offset"); rejects("UIStroke", "Offset")
      ok("Frame", "SelectionImageObject", 1); ok("TextButton", "SelectionImageObject", 1); rejects("UIStroke", "SelectionImageObject")
    end)
  end)
  h.it("single-owner properties reject every other class", function()
    withStrict(function()
      ok("UIStroke", "Thickness", 2); ok("UIStroke", "ApplyStrokeMode", 1); ok("UIStroke", "LineJoinMode", 1)
      rejects("Frame", "Thickness"); rejects("UIGradient", "ApplyStrokeMode")
      ok("CanvasGroup", "GroupTransparency", 0.5); ok("CanvasGroup", "GroupColor3", 1); rejects("Frame", "GroupTransparency")
      ok("UIScale", "Scale", 0.9); rejects("Frame", "Scale"); rejects("UIStroke", "Scale")
      ok("ScrollingFrame", "CanvasSize", 1); ok("ScrollingFrame", "CanvasPosition", 1); ok("ScrollingFrame", "ScrollBarThickness", 4)
      ok("ScrollingFrame", "ScrollBarImageTransparency", 1); ok("ScrollingFrame", "AutomaticCanvasSize", 1)
      rejects("Frame", "CanvasSize"); rejects("Frame", "ScrollBarThickness"); rejects("CanvasGroup", "CanvasPosition")
      ok("UICorner", "CornerRadius", 1); rejects("Frame", "CornerRadius")
      ok("UISizeConstraint", "MinSize", 1); ok("UISizeConstraint", "MaxSize", 1); rejects("Frame", "MinSize")
    end)
  end)
  h.it("keeps text/image/button rules and splits TextBox-only props", function()
    withStrict(function()
      ok("TextLabel", "Text", "x"); ok("TextButton", "TextSize", 12); ok("TextBox", "TextColor3", 1)
      rejects("Frame", "Text"); rejects("ImageLabel", "TextSize")
      for _, p in ipairs({ "PlaceholderText", "PlaceholderColor3", "ClearTextOnFocus", "TextEditable", "CursorPosition", "MultiLine" }) do
        ok("TextBox", p, 1); rejects("TextLabel", p); rejects("TextButton", p)
      end
      ok("ImageLabel", "Image", "rbx"); ok("ImageButton", "SliceCenter", 1); rejects("Frame", "Image"); rejects("TextLabel", "ImageColor3")
      ok("TextButton", "AutoButtonColor", false); ok("ImageButton", "Modal", true); rejects("TextLabel", "AutoButtonColor"); rejects("Frame", "Style")
      ok("Frame", "BackgroundColor3", 1); ok("UIStroke", "Enabled", true) -- unlisted props are never gated
    end)
  end)
  h.it("lenient mode stores everything so unit tests stay terse", function()
    h.expect(mockmod.strict).toBe(false)
    local f = Instance.new("Frame"); f.Thickness = 2; f.Text = "x"; f.CanvasSize = 1
    h.expect(f.Thickness).toBe(2)
  end)
end)

h.describe("helper", function()
  h.it("toBeCloseTo compares within eps", function()
    h.expect(0.1 + 0.2).toBeCloseTo(0.3)
    h.expect(1).toBeCloseTo(1.05, 0.1)
    h.expect(function() h.expect(1).toBeCloseTo(1.05) end).toThrow("expected 1.05")
    h.expect(function() h.expect("x").toBeCloseTo(1) end).toThrow("got x")
  end)
  h.it("withReducedMotion disables Animate for fn and restores it, even on error", function()
    local R = h.loadLib()
    h.expect(R.Animate.isEnabled()).toBe(true)
    local inside
    h.withReducedMotion(R, function() inside = R.Animate.isEnabled() end)
    h.expect(inside).toBe(false)
    h.expect(R.Animate.isEnabled()).toBe(true)
    h.expect(function() h.withReducedMotion(R, function() error("boom") end) end).toThrow("boom")
    h.expect(R.Animate.isEnabled()).toBe(true)
    -- reduced: the goal lands instantly and TweenService is never asked for a tween
    h.mock.resetTweens()
    local f = Instance.new("Frame")
    h.withReducedMotion(R, function() R.Animate.to(f, "fast", { BackgroundTransparency = 0.5 }) end)
    h.expect(f.BackgroundTransparency).toBe(0.5)
    h.expect(h.mock.tweenCount()).toBe(0)
  end)
end)

h.run()
