local h = require("tests.helper")
local R = h.loadLib()
local NumberBox, Create, Config = R.NumberBox, R.Create, R.Config

h.describe("numberbox", function()
  h.it("clamps to range and persists", function()
    local cfg = Config.new({ FileName = "NB", AutoSave = false })
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Vol", Default = 50, Min = 0, Max = 100, Flag = "vol", Config = cfg })
    h.expect(nb.GetValue()).toBe(50)
    nb.SetValue(150)
    h.expect(nb.GetValue()).toBe(100)   -- clamped to Max
    h.expect(cfg:Get("vol")).toBe(100)
    nb.SetValue(-5)
    h.expect(nb.GetValue()).toBe(0)     -- clamped to Min
  end)
  h.it("places the box on the right half with Text; Description renders", function()
    local a = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local c = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Description = "How many", Default = 1 })
    h.expect(c.Frame:FindFirstChild("Description").Text).toBe("How many")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(nb.Frame.BackgroundTransparency).toBe(0)
    h.expect(nb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(nb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
  h.it("compact format displays abbreviated and parses typed input", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Gold", Default = 1500, Format = "compact" })
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(input.Text).toBe("1.5k")
    input.Text = "2k"; input.FocusLost:Fire()
    h.expect(nb.GetValue()).toBe(2000)
    h.expect(input.Text).toBe("2k")
  end)
  h.it("shows the raw number while focused", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Gold", Default = 1500, Format = "compact" })
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Focused:Fire()
    h.expect(input.Text).toBe("1500")
  end)
  h.it("disables minus at Min and plus at Max", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
    local box = nb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("Minus").Active).toBe(false)
    h.expect(box:FindFirstChild("Plus").Active).toBe(true)
    nb.SetValue(10)
    h.expect(box:FindFirstChild("Minus").Active).toBe(true)
    h.expect(box:FindFirstChild("Plus").Active).toBe(false)
  end)
  h.it("step glyphs rest at the structural tint and dim to Opacity.disabled at a bound (1.4)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
    local box = nb.Frame:FindFirstChild("Box")
    local minusImg = box:FindFirstChild("Minus"):FindFirstChildOfClass("ImageLabel")
    local plusImg = box:FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
    h.expect(minusImg.ImageColor3).toBe(R.Theme.Colors.mutedForeground) -- structural, not the accent
    h.expect(plusImg.ImageColor3).toBe(R.Theme.Colors.mutedForeground)
    h.expect(minusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)  -- at Min
    h.expect(plusImg.ImageTransparency).toBe(0)
    nb.SetValue(10)
    h.expect(minusImg.ImageTransparency).toBe(0)
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)   -- at Max
    -- the dim is a Motion.fast tween on ImageTransparency, not a colour swap or a snap
    local tws = h.mock.tweensFor(plusImg)
    h.expect(#tws >= 1).toBeTruthy()
    local last = tws[#tws]
    h.expect(last.Goal.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(last.Goal.ImageColor3).toBeNil()
    h.expect(last.Info.Time).toBe(R.Theme.Motion.fast)
    -- a SetValue that stays inside the range never re-tweens an unchanged glyph
    local before = #h.mock.tweensFor(minusImg)
    nb.SetValue(5); nb.SetValue(7)
    h.expect(#h.mock.tweensFor(minusImg)).toBe(before)
  end)
  h.it("bound dim lands instantly under reduced motion", function()
    h.withReducedMotion(R, function()
      local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
      local plusImg = nb.Frame:FindFirstChild("Box"):FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
      nb.SetValue(10)
      h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
      h.expect(#h.mock.tweensFor(plusImg)).toBe(0)
    end)
  end)
  h.it("glyph tint and bound dim survive a themer closure re-derive", function()
    local closure
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 10, Min = 0, Max = 10,
      AccentReg = function(fn) closure = fn; return function() end end })
    local box = nb.Frame:FindFirstChild("Box")
    local plusImg = box:FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
    closure("mode")
    h.expect(plusImg.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.structural])
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(box:FindFirstChild("Plus").Active).toBe(false)
  end)
  h.it("Box stroke shows the ring at focusThickness while the input is focused (1.7)", function()
    local closure
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 1,
      AccentReg = function(fn) closure = fn; return function() end end })
    local box = nb.Frame:FindFirstChild("Box")
    local stroke = box:FindFirstChildOfClass("UIStroke")
    local input = box:FindFirstChild("Input")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    input.Focused:Fire()
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
    closure("accent")                                   -- reskin while focused keeps the ring
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    input.FocusLost:Fire()
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
  end)
  h.it("text parts carry their theme Font roles (1.2)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Description = "d", Default = 1 })
    local title = nb.Frame:FindFirstChild("Title")
    h.expect(title.TextSize).toBe(R.Theme.Font.label.Size)
    h.expect(title.FontFace.Weight).toBe(R.Theme.Font.label.Weight)
    h.expect(nb.Frame:FindFirstChild("Description").TextSize).toBe(R.Theme.Font.muted.Size)
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(input.TextSize).toBe(R.Theme.Font.body.Size)
    h.expect(input.Font).toBe(h.roblox.Enum.Font.BuilderSans)
  end)
  h.it("scroll wheel adjusts by step while the pointer is over the box", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 5, Min = 0, Max = 100, Step = 5 })
    local box = nb.Frame:FindFirstChild("Box")
    box.MouseEnter:Fire()   -- 2.16: the wheel is gated on a real hover (or focus)
    box.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = 1 } })
    h.expect(nb.GetValue()).toBe(10)
    box.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = -1 } })
    h.expect(nb.GetValue()).toBe(5)
  end)
  h.it("press-and-hold repeats and stops on release", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 1000, Step = 1 })
    local plus = nb.Frame:FindFirstChild("Box"):FindFirstChild("Plus")
    plus.MouseButton1Down:Fire()
    h.expect(nb.GetValue()).toBe(1)
    for _ = 1, 50 do h.mock.stepHeartbeat(0.1) end
    h.expect(nb.GetValue() > 1).toBeTruthy()
    plus.MouseButton1Up:Fire()
    local v = nb.GetValue()
    for _ = 1, 10 do h.mock.stepHeartbeat(0.1) end
    h.expect(nb.GetValue()).toBe(v)
  end)
  h.it("the wheel does nothing without hover, and stops again after MouseLeave (2.16)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 5, Min = 0, Max = 100, Step = 5 })
    local box = nb.Frame:FindFirstChild("Box")
    local wheel = { UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = 1 } }
    -- a wheel event that merely passes through the row must keep scrolling the panel behind it
    box.InputChanged:Fire(wheel)
    h.expect(nb.GetValue()).toBe(5)
    box.MouseEnter:Fire(); box.InputChanged:Fire(wheel)
    h.expect(nb.GetValue()).toBe(10)
    box.MouseLeave:Fire(); box.InputChanged:Fire(wheel)
    h.expect(nb.GetValue()).toBe(10)
    -- a focused field keeps the wheel even when the pointer has wandered off
    box:FindFirstChild("Input").Focused:Fire()
    box.InputChanged:Fire(wheel)
    h.expect(nb.GetValue()).toBe(15)
  end)
  h.it("step buttons carry a hover wash and squash their glyph on press (2.7)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 5, Min = 0, Max = 100 })
    local plus = nb.Frame:FindFirstChild("Box"):FindFirstChild("Plus")
    local img = plus:FindFirstChildOfClass("ImageLabel")
    local wash = plus:FindFirstChild("Hover")
    h.expect(wash ~= nil).toBeTruthy()
    h.expect(wash.ZIndex).toBe(0)                      -- above the button fill, below the glyph
    h.expect(wash.BackgroundTransparency).toBe(1)
    plus.MouseEnter:Fire()
    h.expect(wash.BackgroundTransparency).toBe(R.Theme.Opacity.hoverWash)
    plus.MouseButton1Down:Fire()
    h.expect(wash.BackgroundTransparency).toBe(R.Theme.Opacity.pressWash)
    h.expect(img:FindFirstChildOfClass("UIScale").Scale).toBe(R.Theme.Motion.pressScale)
    plus.MouseButton1Up:Fire()
    h.expect(img:FindFirstChildOfClass("UIScale").Scale).toBe(1)
    plus.MouseLeave:Fire()
    h.expect(wash.BackgroundTransparency).toBe(1)
  end)
  h.it("a press refused at a bound bumps the box and lands back on its own offset (2.16)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
    local box = nb.Frame:FindFirstChild("Box")
    local x0 = box.Position.X.Offset
    h.mock.resetTweens()
    box:FindFirstChild("Minus").MouseButton1Down:Fire()
    h.expect(nb.GetValue()).toBe(0)                    -- refused, so nothing stepped
    local tws = h.mock.tweensFor(box)
    h.expect(#tws).toBe(2)                             -- out and back, nothing else moves the Box
    h.expect(tws[1].Goal.Position.X.Offset).toBe(x0 - R.Theme.Motion.bumpPx)
    h.expect(tws[2].Goal.Position.X.Offset).toBe(x0)
    h.expect(box.Position.X.Offset).toBe(x0)
    -- the other side bumps the other way
    nb.SetValue(10); h.mock.resetTweens()
    box:FindFirstChild("Plus").MouseButton1Down:Fire()
    h.expect(h.mock.tweensFor(box)[1].Goal.Position.X.Offset).toBe(x0 + R.Theme.Motion.bumpPx)
    h.expect(box.Position.X.Offset).toBe(x0)
  end)
  h.it("reduced motion: a refused press does not move the box at all", function()
    h.withReducedMotion(R, function()
      local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
      local box = nb.Frame:FindFirstChild("Box")
      local x0 = box.Position.X.Offset
      h.mock.resetTweens()
      box:FindFirstChild("Minus").MouseButton1Down:Fire()
      h.expect(#h.mock.tweensFor(box)).toBe(0)
      h.expect(box.Position.X.Offset).toBe(x0)
    end)
  end)
  h.it("SetEnabled(false) dims the field, blocks stepping and the wheel, but still applies SetValue (2.8)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 5, Min = 0, Max = 100, Step = 5 })
    local box = nb.Frame:FindFirstChild("Box")
    local input, plus = box:FindFirstChild("Input"), box:FindFirstChild("Plus")
    local plusImg = plus:FindFirstChildOfClass("ImageLabel")
    nb.SetEnabled(false)
    h.expect(box.BackgroundTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(input.TextEditable).toBe(false)
    plus.MouseButton1Down:Fire()
    for _ = 1, 10 do h.mock.stepHeartbeat(0.1) end     -- the hold-repeat never starts either
    box.MouseEnter:Fire()
    box.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = 1 } })
    h.expect(nb.GetValue()).toBe(5)
    nb.SetValue(100)                                    -- config/apply path still applies (2.8a)
    h.expect(nb.GetValue()).toBe(100)
    nb.SetEnabled(true)
    h.expect(box.BackgroundTransparency).toBe(0)
    h.expect(input.TextEditable).toBe(true)
    -- re-enabling restores each part's REST, so a glyph sitting at Max stays dimmed
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(box:FindFirstChild("Minus"):FindFirstChildOfClass("ImageLabel").ImageTransparency).toBe(0)
  end)
end)

h.run()
