local h = require("tests.helper")
local R = h.loadLib()
local NumberBox, Create, Config = R.NumberBox, R.Create, R.Config

h.describe("numberbox", function()
  h.it("clamps to range and persists", function()
    local cfg = Config.new({ FileName = "NB", AutoSave = false })
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Vol", Default = 50, Min = 0, Max = 100, Flag = "vol", Config = cfg })
    h.expect(nb.GetValue()).toBe(50)
    nb.SetValue(150)
    h.expect(nb.GetValue()).toBe(100)   -- clamped to Max
    h.expect(cfg:Get("vol")).toBe(100)
    nb.SetValue(-5)
    h.expect(nb.GetValue()).toBe(0)     -- clamped to Min
  end)
  h.it("places the box on the right half with Text; Description renders", function()
    local a = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local c = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Description = "How many", Default = 1 })
    h.expect(c.Frame:FindFirstChild("Description").Text).toBe("How many")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(nb.Frame.BackgroundTransparency).toBe(0)
    h.expect(nb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(nb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
  h.it("compact format displays abbreviated and parses typed input", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Gold", Default = 1500, Format = "compact" })
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(input.Text).toBe("1.5k")
    input.Text = "2k"; input.FocusLost:Fire()
    h.expect(nb.GetValue()).toBe(2000)
    h.expect(input.Text).toBe("2k")
  end)
  h.it("shows the raw number while focused", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Gold", Default = 1500, Format = "compact" })
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Focused:Fire()
    h.expect(input.Text).toBe("1500")
  end)
  h.it("disables minus at Min and plus at Max", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
    local box = nb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("Minus").Active).toBe(false)
    h.expect(box:FindFirstChild("Plus").Active).toBe(true)
    nb.SetValue(10)
    h.expect(box:FindFirstChild("Minus").Active).toBe(true)
    h.expect(box:FindFirstChild("Plus").Active).toBe(false)
  end)
  h.it("step glyphs rest at the structural tint and dim to Opacity.disabled at a bound (1.4)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
    local box = nb.Frame:FindFirstChild("Box")
    local minusImg = box:FindFirstChild("Minus"):FindFirstChildOfClass("ImageLabel")
    local plusImg = box:FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
    h.expect(minusImg.ImageColor3).toBe(R.Theme.Colors.mutedForeground) -- structural, not the accent
    h.expect(plusImg.ImageColor3).toBe(R.Theme.Colors.mutedForeground)
    h.expect(minusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)  -- at Min
    h.expect(plusImg.ImageTransparency).toBe(0)
    nb.SetValue(10)
    h.expect(minusImg.ImageTransparency).toBe(0)
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)   -- at Max
    -- the dim is a Motion.fast tween on ImageTransparency, not a colour swap or a snap
    local tws = h.mock.tweensFor(plusImg)
    h.expect(#tws >= 1).toBeTruthy()
    local last = tws[#tws]
    h.expect(last.Goal.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(last.Goal.ImageColor3).toBeNil()
    h.expect(last.Info.Time).toBe(R.Theme.Motion.fast)
    -- a SetValue that stays inside the range never re-tweens an unchanged glyph
    local before = #h.mock.tweensFor(minusImg)
    nb.SetValue(5); nb.SetValue(7)
    h.expect(#h.mock.tweensFor(minusImg)).toBe(before)
  end)
  h.it("bound dim lands instantly under reduced motion", function()
    h.withReducedMotion(R, function()
      local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 10 })
      local plusImg = nb.Frame:FindFirstChild("Box"):FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
      nb.SetValue(10)
      h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
      h.expect(#h.mock.tweensFor(plusImg)).toBe(0)
    end)
  end)
  h.it("glyph tint and bound dim survive a themer closure re-derive", function()
    local closure
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 10, Min = 0, Max = 10,
      AccentReg = function(fn) closure = fn; return function() end end })
    local box = nb.Frame:FindFirstChild("Box")
    local plusImg = box:FindFirstChild("Plus"):FindFirstChildOfClass("ImageLabel")
    closure("mode")
    h.expect(plusImg.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.structural])
    h.expect(plusImg.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(box:FindFirstChild("Plus").Active).toBe(false)
  end)
  h.it("Box stroke shows the ring at focusThickness while the input is focused (1.7)", function()
    local closure
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 1,
      AccentReg = function(fn) closure = fn; return function() end end })
    local box = nb.Frame:FindFirstChild("Box")
    local stroke = box:FindFirstChildOfClass("UIStroke")
    local input = box:FindFirstChild("Input")
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
    input.Focused:Fire()
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
    closure("accent")                                   -- reskin while focused keeps the ring
    h.expect(stroke.Color).toBe(R.Theme.Colors.ring)
    input.FocusLost:Fire()
    h.expect(stroke.Color).toBe(R.Theme.Colors.border)
    h.expect(stroke.Thickness).toBe(1)
  end)
  h.it("text parts carry their theme Font roles (1.2)", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Description = "d", Default = 1 })
    local title = nb.Frame:FindFirstChild("Title")
    h.expect(title.TextSize).toBe(R.Theme.Font.label.Size)
    h.expect(title.FontFace.Weight).toBe(R.Theme.Font.label.Weight)
    h.expect(nb.Frame:FindFirstChild("Description").TextSize).toBe(R.Theme.Font.muted.Size)
    local input = nb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(input.TextSize).toBe(R.Theme.Font.body.Size)
    h.expect(input.Font).toBe(h.roblox.Enum.Font.BuilderSans)
  end)
  h.it("scroll wheel adjusts by step", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 5, Min = 0, Max = 100, Step = 5 })
    local box = nb.Frame:FindFirstChild("Box")
    box.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = 1 } })
    h.expect(nb.GetValue()).toBe(10)
    box.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseWheel, Position = { Z = -1 } })
    h.expect(nb.GetValue()).toBe(5)
  end)
  h.it("press-and-hold repeats and stops on release", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "N", Default = 0, Min = 0, Max = 1000, Step = 1 })
    local plus = nb.Frame:FindFirstChild("Box"):FindFirstChild("Plus")
    plus.MouseButton1Down:Fire()
    h.expect(nb.GetValue()).toBe(1)
    for _ = 1, 50 do h.mock.stepHeartbeat(0.1) end
    h.expect(nb.GetValue() > 1).toBeTruthy()
    plus.MouseButton1Up:Fire()
    local v = nb.GetValue()
    for _ = 1, 10 do h.mock.stepHeartbeat(0.1) end
    h.expect(nb.GetValue()).toBe(v)
  end)
end)

h.run()
