local h = require("tests.helper")

-- Every case starts from a desktop baseline (mouse present, no touch, keyboard as last input)
-- because Recipes.hover gates on Device.SupportsHover() and the mock services persist across tests.
local function ctx()
  local R = h.loadLib()
  local uis = h.roblox.game:GetService("UserInputService")
  uis.MouseEnabled = true; uis.TouchEnabled = false
  h.mock.lastInputType = nil
  h.mock.resetTweens()
  return R, R.Recipes, R.Theme.new()
end

local function mk(cls, name, parent)
  local i = h.roblox.Instance.new(cls)
  i.Name = name
  if parent then i.Parent = parent end
  return i
end

local function lastGoalFor(inst)
  local tws = h.mock.tweensFor(inst)
  return tws[#tws]
end

-- ---- hover: wash ----------------------------------------------------------------------------
h.describe("recipes.hover wash", function()
  h.it("builds nothing until the first hover, then a 'Hover' child with the plan's geometry and tokens", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    local hv = Recipes.hover(host, { theme = theme, host = host, corner = theme.Radius.md, inset = { x = 12, y = 8 } })
    -- bind time costs no instance at all: the wash is invisible at rest and most controls
    -- (every one of them on a touch device) are never pointed at
    h.expect(host:FindFirstChild("Hover")).toBe(nil)
    h.expect(#host:GetChildren()).toBe(0)
    h.expect(hv.Frame).toBe(nil)
    host.MouseEnter:Fire()
    local wash = host:FindFirstChild("Hover")
    h.expect(wash ~= nil).toBeTruthy()
    h.expect(hv.Frame).toBe(wash)
    h.expect(wash.ClassName).toBe("Frame")
    h.expect(wash.Size.X.Scale).toBe(1); h.expect(wash.Size.X.Offset).toBe(24)
    h.expect(wash.Size.Y.Scale).toBe(1); h.expect(wash.Size.Y.Offset).toBe(16)
    h.expect(wash.Position.X.Offset).toBe(-12); h.expect(wash.Position.Y.Offset).toBe(-8)
    h.expect(wash.ZIndex).toBe(0)
    h.expect(wash.Active).toBe(false)
    h.expect(wash.BackgroundColor3).toBe(theme.Colors.foreground) -- identity: reskin-able token
    h.expect(wash:FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(theme.Radius.md)
    h.expect(host:FindFirstChild("Active")).toBe(nil) -- tab_test pins: never named 'Active'
    -- built fully transparent: the Enter tween above is what makes it visible, so its rest value
    -- is read back on the way out rather than before it exists
    host.MouseLeave:Fire()
    h.expect(wash.BackgroundTransparency).toBe(1)
    h.expect(#host:GetChildren()).toBe(1)                         -- and never a second one
  end)
  h.it("tweens hoverWash / pressWash / back to 1 on Enter / Down / Up / Leave", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    Recipes.hover(host, { theme = theme })
    host.MouseEnter:Fire()
    local wash = host:FindFirstChild("Hover")   -- the Enter itself is what builds it
    local tw = lastGoalFor(wash)
    h.expect(tw.Goal.BackgroundTransparency).toBe(theme.Opacity.hoverWash)
    h.expect(tw.Info.Time).toBe(theme.Motion.hover)
    host.MouseButton1Down:Fire()
    tw = lastGoalFor(wash)
    h.expect(tw.Goal.BackgroundTransparency).toBe(theme.Opacity.pressWash)
    h.expect(tw.Info.Time).toBe(theme.Motion.press)
    host.MouseButton1Up:Fire() -- pointer still over the row: back to the hover level, not rest
    h.expect(wash.BackgroundTransparency).toBe(theme.Opacity.hoverWash)
    host.MouseLeave:Fire()
    h.expect(wash.BackgroundTransparency).toBe(1)
  end)
  h.it("host defaults to hit, inset defaults to 0 and accepts the positional {x, y} form", function()
    local R, Recipes, theme = ctx()
    local a = mk("TextButton", "A")
    Recipes.hover(a, { theme = theme })
    a.MouseEnter:Fire()
    local wa = a:FindFirstChild("Hover")
    h.expect(wa.Size.X.Offset).toBe(0); h.expect(wa.Position.Y.Offset).toBe(0)
    h.expect(wa:FindFirstChildOfClass("UICorner")).toBe(nil)
    local b = mk("TextButton", "B")
    Recipes.hover(b, { theme = theme, inset = { 4, 2 } })
    b.MouseEnter:Fire()
    local wb = b:FindFirstChild("Hover")
    h.expect(wb.Size.X.Offset).toBe(8); h.expect(wb.Size.Y.Offset).toBe(4)
    h.expect(wb.Position.X.Offset).toBe(-4); h.expect(wb.Position.Y.Offset).toBe(-2)
  end)
  h.it("a touch tap (Enter/Down/Up without Leave) returns the wash to rest on Up", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    Recipes.hover(host, { theme = theme })
    h.mock.lastInputType = h.roblox.Enum.UserInputType.Touch
    host.MouseEnter:Fire(); host.MouseButton1Down:Fire(); host.MouseButton1Up:Fire()
    local wash = host:FindFirstChild("Hover")
    h.expect(wash.BackgroundTransparency).toBe(1)
  end)
  h.it("reskin re-reads theme.Colors.foreground after a mode swap", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    local hv = Recipes.hover(host, { theme = theme })
    host.MouseEnter:Fire()                       -- the wash has to exist to be re-skinned
    local wash = host:FindFirstChild("Hover")
    R.Theme.applyMode(theme, "light")
    h.expect(wash.BackgroundColor3 ~= theme.Colors.foreground).toBeTruthy()
    hv.reskin()
    h.expect(wash.BackgroundColor3).toBe(theme.Colors.foreground)
  end)
  h.it("a mode swap before the first hover still washes in the CURRENT palette", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    local hv = Recipes.hover(host, { theme = theme })
    local dark = theme.Colors.foreground
    R.Theme.applyMode(theme, "light")            -- nothing to reskin yet; reskin must not care
    hv.reskin()
    host.MouseEnter:Fire()
    local wash = host:FindFirstChild("Hover")
    h.expect(wash.BackgroundColor3).toBe(theme.Colors.foreground)
    h.expect(wash.BackgroundColor3 ~= dark).toBeTruthy()   -- not the palette live at bind time
  end)
  h.it("a press that never saw an Enter still builds the wash and presses it", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    Recipes.hover(host, { theme = theme })
    host.MouseButton1Down:Fire()
    local wash = host:FindFirstChild("Hover")
    h.expect(wash ~= nil).toBeTruthy()
    h.expect(wash.BackgroundTransparency).toBe(theme.Opacity.pressWash)
  end)
  h.it("disconnect() detaches every handler", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    local hv = Recipes.hover(host, { theme = theme })
    hv.disconnect()
    h.mock.resetTweens()
    host.MouseEnter:Fire(); host.MouseButton1Down:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
    h.expect(host:FindFirstChild("Hover")).toBe(nil)   -- and a released handle never builds one
    h.expect(hv.Frame).toBe(nil)
  end)
  h.it("applies goals instantly with no tween under reduced motion", function()
    local R, Recipes, theme = ctx()
    local host = mk("TextButton", "Row")
    Recipes.hover(host, { theme = theme })
    h.withReducedMotion(R, function()
      h.mock.resetTweens()
      host.MouseEnter:Fire()
      local wash = host:FindFirstChild("Hover")   -- built by the Enter, without a tween of its own
      h.expect(wash.BackgroundTransparency).toBe(theme.Opacity.hoverWash)
      host.MouseLeave:Fire()
      h.expect(wash.BackgroundTransparency).toBe(1)
      h.expect(h.mock.tweenCount()).toBe(0)
    end)
  end)
end)

-- ---- hover: fill / text / gating ------------------------------------------------------------
h.describe("recipes.hover fill and text", function()
  h.it("fill creates no Frame and tweens only host.BackgroundTransparency (colour untouched)", function()
    local R, Recipes, theme = ctx()
    local row = mk("Frame", "Row")
    row.BackgroundColor3 = theme.Colors.surface
    row.BackgroundTransparency = 0
    Recipes.hover(row, { theme = theme, kind = "fill" })
    h.expect(row:FindFirstChild("Hover")).toBe(nil)
    h.expect(#row:GetChildren()).toBe(0)
    row.MouseEnter:Fire()
    local tw = lastGoalFor(row)
    h.expect(tw.Goal.BackgroundTransparency).toBe(theme.Opacity.rowHover)
    h.expect(tw.Goal.BackgroundColor3).toBe(nil)
    row.MouseLeave:Fire()
    h.expect(row.BackgroundTransparency).toBe(0) -- rest captured at bind, not a literal 1
    h.expect(row.BackgroundColor3).toBe(theme.Colors.surface)
  end)
  h.it("fill on a plain Frame presses through InputBegan/InputEnded with hoverAlpha/pressAlpha overrides", function()
    local R, Recipes, theme = ctx()
    local row = mk("Frame", "Row")
    row.BackgroundTransparency = 1
    Recipes.hover(row, { theme = theme, kind = "fill", hoverAlpha = theme.Opacity.tabHover, pressAlpha = theme.Opacity.tabPress })
    row.MouseEnter:Fire()
    h.expect(row.BackgroundTransparency).toBe(theme.Opacity.tabHover)
    row.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1 })
    h.expect(row.BackgroundTransparency).toBe(theme.Opacity.tabPress)
    row.InputEnded:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1 })
    h.expect(row.BackgroundTransparency).toBe(theme.Opacity.tabHover)
    row.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement }) -- not a press
    h.expect(row.BackgroundTransparency).toBe(theme.Opacity.tabHover)
  end)
  h.it("text tints label muted->foreground (and the icon) on Enter, back on Leave", function()
    local R, Recipes, theme = ctx()
    local btn = mk("TextButton", "Tab")
    local label = mk("TextLabel", "Label", btn); label.TextColor3 = theme.Colors.mutedForeground
    local icon = mk("ImageLabel", "Icon", btn); icon.ImageColor3 = theme.Colors.mutedForeground
    Recipes.hover(btn, { theme = theme, kind = "text", label = label, icon = icon })
    h.expect(btn:FindFirstChild("Hover")).toBe(nil)
    btn.MouseEnter:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.foreground)
    h.expect(icon.ImageColor3).toBe(theme.Colors.foreground)
    btn.MouseLeave:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.mutedForeground)
    h.expect(icon.ImageColor3).toBe(theme.Colors.mutedForeground)
  end)
  h.it("text accepts token names for rest/hover and reskin repaints the current state by name", function()
    local R, Recipes, theme = ctx()
    local btn = mk("TextButton", "Tab")
    local label = mk("TextLabel", "Label", btn)
    local hv = Recipes.hover(btn, { theme = theme, kind = "text", label = label, rest = "primary", hover = "destructive" })
    btn.MouseEnter:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.destructive)
    R.Theme.applyMode(theme, "light")
    hv.reskin()
    h.expect(label.TextColor3).toBe(theme.Colors.destructive)
    btn.MouseLeave:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.primary)
  end)
  h.it("is skipped entirely (no Frame, no handlers) when the device has no mouse", function()
    local R, Recipes, theme = ctx()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.MouseEnabled = false
    local host = mk("TextButton", "Row")
    local ok, hv = pcall(Recipes.hover, host, { theme = theme })
    uis.MouseEnabled = true
    h.expect(ok).toBe(true)
    h.expect(host:FindFirstChild("Hover")).toBe(nil)
    h.expect(hv.Frame).toBe(nil)
    h.mock.resetTweens()
    host.MouseEnter:Fire(); host.MouseButton1Down:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
    hv.reskin(); hv.disconnect() -- no-op handle still honours the contract
  end)
end)

-- ---- press ----------------------------------------------------------------------------------
h.describe("recipes.press", function()
  h.it("adds one UIScale to scaleHost and dips to pressScale on Down, springs to 1 on Up", function()
    local R, Recipes, theme = ctx()
    local hit = mk("TextButton", "Row")
    local inner = mk("Frame", "Content", hit)
    local pr = Recipes.press(hit, inner, { theme = theme })
    local us = inner:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(pr.Scale).toBe(us)
    h.expect(hit:FindFirstChildOfClass("UIScale")).toBe(nil) -- never on the row (UIListLayout reflow)
    hit.MouseButton1Down:Fire()
    local tw = lastGoalFor(us)
    h.expect(tw.Goal.Scale).toBe(theme.Motion.pressScale)
    h.expect(tw.Info.Time).toBe(theme.Motion.press)
    hit.MouseButton1Up:Fire()
    tw = lastGoalFor(us)
    h.expect(tw.Goal.Scale).toBe(1)
    h.expect(tw.Info.Time).toBe(theme.Motion.release)
    h.expect(tw.Info.EasingStyle.Name).toBe("Back")
    h.expect(tw.Info.EasingDirection.Name).toBe("Out")
  end)
  h.it("reuses an existing UIScale and releases on Leave only while pressed", function()
    local R, Recipes, theme = ctx()
    local hit = mk("TextButton", "Row")
    local inner = mk("Frame", "Content", hit)
    local existing = mk("UIScale", "Scale", inner)
    local pr = Recipes.press(hit, inner, { theme = theme })
    h.expect(pr.Scale).toBe(existing)
    local n = 0
    for _, c in ipairs(inner:GetChildren()) do if c.ClassName == "UIScale" then n = n + 1 end end
    h.expect(n).toBe(1)
    h.mock.resetTweens()
    hit.MouseLeave:Fire() -- not pressed: nothing to release
    h.expect(h.mock.tweenCount()).toBe(0)
    hit.MouseButton1Down:Fire(); hit.MouseLeave:Fire()
    h.expect(existing.Scale).toBe(1)
    pr.disconnect()
    h.mock.resetTweens()
    hit.MouseButton1Down:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
  end)
  h.it("creates no UIScale when scaleHost is nil (wash/fill dip only)", function()
    local R, Recipes, theme = ctx()
    local hit = mk("TextButton", "Tab")
    local pr = Recipes.press(hit, nil, { theme = theme })
    h.expect(pr.Scale).toBe(nil)
    h.expect(hit:FindFirstChildOfClass("UIScale")).toBe(nil)
    h.mock.resetTweens()
    hit.MouseButton1Down:Fire(); hit.MouseButton1Up:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
    h.expect(hit:FindFirstChildOfClass("UIScale")).toBe(nil)
    pr.disconnect()
  end)
end)

-- ---- iconButton -----------------------------------------------------------------------------
h.describe("recipes.iconButton", function()
  local function rig(theme, size)
    local bar = mk("Frame", "TitleBar")
    local btn = mk("ImageButton", "Close", bar)
    btn.Size = h.roblox.UDim2.new(0, size or 18, 0, size or 18)
    btn.Position = h.roblox.UDim2.new(1, -18, 0.5, -9)
    btn.ZIndex = 3
    return bar, btn
  end
  h.it("creates a transparent '<Name>Hit' sibling centred on the glyph, one ZIndex above it", function()
    local R, Recipes, theme = ctx()
    local bar, btn = rig(theme)
    local ib = Recipes.iconButton(btn, { theme = theme, icon = "x", rest = "mutedForeground", hover = "destructive" })
    local hit = bar:FindFirstChild("CloseHit")
    h.expect(hit ~= nil).toBeTruthy()
    h.expect(ib.Hit).toBe(hit)
    h.expect(hit.ClassName).toBe("ImageButton")
    h.expect(hit.Parent).toBe(bar)
    h.expect(hit.Size.X.Offset).toBe(theme.Sizes.iconButton); h.expect(hit.Size.Y.Offset).toBe(theme.Sizes.iconButton)
    h.expect(hit.AnchorPoint.X).toBe(0.5); h.expect(hit.AnchorPoint.Y).toBe(0.5)
    h.expect(hit.Position.X.Scale).toBe(1); h.expect(hit.Position.X.Offset).toBe(-9)
    h.expect(hit.Position.Y.Scale).toBe(0.5); h.expect(hit.Position.Y.Offset).toBe(0)
    h.expect(hit.ZIndex).toBe(4)
    h.expect(hit.AutoButtonColor).toBe(false)
    h.expect(hit.Active).toBe(true)
    h.expect(hit.BackgroundTransparency).toBe(1)
    -- glyph button keeps its own size: the ImageButton renders its Image at full Size
    h.expect(btn.Size.X.Offset).toBe(18); h.expect(btn.Size.Y.Offset).toBe(18)
    -- wash lives in the hit with the small radius, once the pointer has actually arrived
    h.expect(hit:FindFirstChild("Hover")).toBe(nil)
    hit.MouseEnter:Fire()
    local wash = hit:FindFirstChild("Hover")
    h.expect(wash ~= nil).toBeTruthy()
    h.expect(wash:FindFirstChildOfClass("UICorner").CornerRadius.Offset).toBe(theme.Radius.sm)
  end)
  h.it("uses Sizes.touchHit on touch devices and honours an explicit hitSize", function()
    local R, Recipes, theme = ctx()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.TouchEnabled = true
    local bar, btn = rig(theme)
    local ib = Recipes.iconButton(btn, { theme = theme, icon = "x" })
    uis.TouchEnabled = false
    h.expect(ib.Hit.Size.X.Offset).toBe(theme.Sizes.touchHit)
    local bar2, btn2 = rig(theme)
    local ib2 = Recipes.iconButton(btn2, { theme = theme, icon = "x", hitSize = 32, parent = bar2 })
    h.expect(ib2.Hit.Size.X.Offset).toBe(32)
    h.expect(ib2.Hit.Parent).toBe(bar2)
  end)
  h.it("hover tint and click run from BOTH the button and the hit", function()
    local R, Recipes, theme = ctx()
    local bar, btn = rig(theme)
    local clicks = 0
    Recipes.iconButton(btn, { theme = theme, icon = "x", rest = "mutedForeground", hover = "destructive",
      onClick = function() clicks = clicks + 1 end })
    local hit = bar:FindFirstChild("CloseHit")
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
    btn.MouseEnter:Fire()
    h.expect(btn.ImageColor3).toBe(theme.Colors.destructive)
    btn.MouseLeave:Fire()
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
    hit.MouseEnter:Fire()
    h.expect(btn.ImageColor3).toBe(theme.Colors.destructive)
    h.expect(hit:FindFirstChild("Hover").BackgroundTransparency).toBe(theme.Opacity.hoverWash)
    hit.MouseLeave:Fire()
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
    btn.MouseButton1Click:Fire(); hit.MouseButton1Click:Fire()
    h.expect(clicks).toBe(2)
  end)
  h.it("reskin re-tints the glyph by token name; disconnect detaches both sources", function()
    local R, Recipes, theme = ctx()
    local bar, btn = rig(theme)
    local ib = Recipes.iconButton(btn, { theme = theme, icon = "minus", rest = "mutedForeground", hover = "primary" })
    R.Theme.applyMode(theme, "light")
    ib.reskin()
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
    ib.disconnect()
    h.mock.resetTweens()
    btn.MouseEnter:Fire(); ib.Hit.MouseEnter:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
  end)
  h.it("still builds the hit target without a mouse, but binds no hover", function()
    local R, Recipes, theme = ctx()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.MouseEnabled = false
    local bar, btn = rig(theme)
    local ok, ib = pcall(Recipes.iconButton, btn, { theme = theme, icon = "x", rest = "mutedForeground", hover = "destructive" })
    uis.MouseEnabled = true
    h.expect(ok).toBe(true)
    h.expect(ib.Hit.Parent).toBe(bar)
    h.expect(ib.Hit:FindFirstChild("Hover")).toBe(nil)
    btn.MouseEnter:Fire()
    h.expect(btn.ImageColor3).toBe(theme.Colors.mutedForeground)
  end)
end)

-- ---- focus ----------------------------------------------------------------------------------
h.describe("recipes.focus", function()
  h.it("thickens the stroke to focusThickness with getColor(true) on Focused and back to rest on FocusLost", function()
    local R, Recipes, theme = ctx()
    local box = mk("TextBox", "Input")
    local stroke = R.Create.stroke(theme.Colors.border, 1)
    stroke.Parent = box
    local seen = {}
    Recipes.focus(stroke, box, function(f) seen[#seen + 1] = f; return f and theme.Colors.ring or theme.Colors.border end, { theme = theme })
    box.Focused:Fire()
    local tw = lastGoalFor(stroke)
    h.expect(tw.Goal.Thickness).toBe(theme.Stroke.focusThickness)
    h.expect(tw.Goal.Color).toBe(theme.Colors.ring)
    h.expect(tw.Info.Time).toBe(theme.Motion.fast)
    h.expect(stroke.Thickness).toBe(2)
    box.FocusLost:Fire()
    h.expect(stroke.Thickness).toBe(1)
    h.expect(stroke.Color).toBe(theme.Colors.border)
    h.expect(seen[1]).toBe(true); h.expect(seen[2]).toBe(false)
  end)
  h.it("follows gamepad SelectionGained/SelectionLost and exposes set() for programmatic focus", function()
    local R, Recipes, theme = ctx()
    local box = mk("TextBox", "Input")
    local stroke = R.Create.stroke(theme.Colors.border, 1); stroke.Parent = box
    local fc = Recipes.focus(stroke, box, function(f) return f and theme.Colors.ring or theme.Colors.border end, { theme = theme })
    box.SelectionGained:Fire()
    h.expect(stroke.Thickness).toBe(theme.Stroke.focusThickness)
    box.SelectionLost:Fire()
    h.expect(stroke.Thickness).toBe(1)
    fc.set(true)
    h.expect(stroke.Thickness).toBe(theme.Stroke.focusThickness)
    h.expect(stroke.Color).toBe(theme.Colors.ring)
    fc.set(false)
    h.expect(stroke.Thickness).toBe(1)
    fc.disconnect()
    h.mock.resetTweens()
    box.Focused:Fire()
    h.expect(h.mock.tweenCount()).toBe(0)
  end)
  h.it("writes an invisible SelectionImageObject via pcall (never detected by reading)", function()
    local R, Recipes, theme = ctx()
    local box = mk("TextBox", "Input")
    local stroke = R.Create.stroke(theme.Colors.border, 1); stroke.Parent = box
    h.expect(box.SelectionImageObject).toBe(nil)
    Recipes.focus(stroke, box, function() return theme.Colors.border end, { theme = theme })
    local sel = box.SelectionImageObject
    h.expect(sel ~= nil).toBeTruthy()
    h.expect(sel.ClassName).toBe("Frame")
    h.expect(sel.BackgroundTransparency).toBe(1)
    h.expect(box:FindFirstChildOfClass("Frame")).toBe(nil) -- unparented: no stray child for tests to trip on
  end)
end)

-- ---- disabled -------------------------------------------------------------------------------
h.describe("recipes.disabled", function()
  h.it("dims every part to Opacity.disabled and restores each part's own rest value", function()
    local R, Recipes, theme = ctx()
    local surface = mk("Frame", "Surface"); surface.BackgroundTransparency = 0
    local label = mk("TextLabel", "Label"); label.TextTransparency = 0.2
    local icon = mk("ImageLabel", "Icon"); icon.ImageTransparency = 0
    local parts = { { surface, "BackgroundTransparency", 0 }, { label, "TextTransparency", 0.2 }, { icon, "ImageTransparency" } }
    Recipes.disabled(parts, true, theme)
    h.expect(surface.BackgroundTransparency).toBe(theme.Opacity.disabled)
    h.expect(label.TextTransparency).toBe(theme.Opacity.disabled)
    h.expect(icon.ImageTransparency).toBe(theme.Opacity.disabled)
    local tw = lastGoalFor(label)
    h.expect(tw.Info.Time).toBe(theme.Motion.fast)
    Recipes.disabled(parts, false, theme)
    h.expect(surface.BackgroundTransparency).toBe(0)
    h.expect(label.TextTransparency).toBe(0.2)
    h.expect(icon.ImageTransparency).toBe(0) -- rest omitted: engine default 0
  end)
  h.it("skips nil parts (optional stroke) and applies instantly under reduced motion", function()
    local R, Recipes, theme = ctx()
    local surface = mk("Frame", "Surface")
    local ok = pcall(Recipes.disabled, { { nil, "Transparency", 0 }, { surface, "BackgroundTransparency", 0 } }, true, theme)
    h.expect(ok).toBe(true)
    h.expect(surface.BackgroundTransparency).toBe(theme.Opacity.disabled)
    h.withReducedMotion(R, function()
      h.mock.resetTweens()
      Recipes.disabled({ { surface, "BackgroundTransparency", 0 } }, false, theme)
      h.expect(surface.BackgroundTransparency).toBe(0)
      h.expect(h.mock.tweenCount()).toBe(0)
    end)
  end)
end)

-- ---- empty ----------------------------------------------------------------------------------
h.describe("recipes.empty", function()
  h.it("builds a hidden 'Empty' frame with a 16px muted icon and muted text; SetVisible toggles it", function()
    local R, Recipes, theme = ctx()
    local body = mk("Frame", "Body")
    local em = Recipes.empty(body, { theme = theme, text = "No rows", icon = "inbox", zIndex = 5 })
    local frame = body:FindFirstChild("Empty")
    h.expect(frame ~= nil).toBeTruthy()
    h.expect(em.Frame).toBe(frame)
    h.expect(frame.Visible).toBe(false)
    h.expect(frame.ZIndex).toBe(5)
    h.expect(frame.BackgroundTransparency).toBe(1)
    local icon = frame:FindFirstChild("Icon")
    h.expect(icon.ClassName).toBe("ImageLabel")
    h.expect(icon.Size.X.Offset).toBe(theme.Sizes.icon); h.expect(icon.Size.Y.Offset).toBe(theme.Sizes.icon)
    h.expect(icon.Image).toBe(R.Icons.get("inbox").Id)
    h.expect(icon.ImageColor3).toBe(theme.Colors.mutedForeground)
    h.expect(icon.ZIndex).toBe(5)
    local text = frame:FindFirstChild("Text")
    h.expect(text.ClassName).toBe("TextLabel")
    h.expect(text.Text).toBe("No rows")
    h.expect(text.TextColor3).toBe(theme.Colors.mutedForeground)
    h.expect(text.TextSize).toBe(theme.Font.muted.Size)
    h.expect(text.Font).toBe(h.roblox.Enum.Font.BuilderSans)
    h.expect(frame:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
    em.SetVisible(true)
    h.expect(frame.Visible).toBe(true)
    em.SetVisible(false)
    h.expect(frame.Visible).toBe(false)
  end)
  h.it("omits the icon when none is given and reskin re-reads mutedForeground", function()
    local R, Recipes, theme = ctx()
    local body = mk("Frame", "Body")
    local em = Recipes.empty(body, { theme = theme, text = "No results" })
    h.expect(em.Frame:FindFirstChild("Icon")).toBe(nil)
    R.Theme.applyMode(theme, "light")
    em.reskin()
    h.expect(em.Frame:FindFirstChild("Text").TextColor3).toBe(theme.Colors.mutedForeground)
  end)
end)

-- ---- scrollbar ------------------------------------------------------------------------------
h.describe("recipes.scrollbar", function()
  h.it("applies thickness, border colour and alpha; no image swap while imageId is ''", function()
    local R, Recipes, theme = ctx()
    local sf = mk("ScrollingFrame", "List")
    local out = Recipes.scrollbar(sf, theme)
    h.expect(out).toBe(sf)
    h.expect(sf.ScrollBarThickness).toBe(theme.Sizes.scrollbar)
    h.expect(sf.ScrollBarImageColor3).toBe(theme.Colors.border)
    h.expect(sf.ScrollBarImageTransparency).toBe(theme.Scrollbar.alpha)
    h.expect(sf.TopImage).toBe(nil); h.expect(sf.MidImage).toBe(nil); h.expect(sf.BottomImage).toBe(nil)
  end)
  h.it("writes Top/Mid/BottomImage once a Scrollbar.imageId is configured", function()
    local R, Recipes = ctx()
    local theme = R.Theme.new({ Scrollbar = { imageId = "rbxassetid://1" } })
    local sf = mk("ScrollingFrame", "List")
    Recipes.scrollbar(sf, theme)
    h.expect(sf.TopImage).toBe("rbxassetid://1")
    h.expect(sf.MidImage).toBe("rbxassetid://1")
    h.expect(sf.BottomImage).toBe("rbxassetid://1")
    h.expect(sf.ScrollBarImageTransparency).toBe(theme.Scrollbar.alpha) -- deepMerge kept the sibling token
  end)
end)

h.run()
