local h = require("tests.helper")
local R = h.loadLib(); local Slider, Create, Config = R.Slider, R.Create, R.Config
h.describe("slider", function()
  h.it("maps value to fill scale, clamps, snaps, persists", function()
    local cfg = Config.new({ FileName = "SL", AutoSave = false })
    local s = Slider.new({ Parent = Create("Frame", {}), Text = "Speed", Min = 0, Max = 100, Default = 50, Flag = "spd", Config = cfg })
    h.expect(s.GetValue()).toBe(50)
    s.SetValue(150); h.expect(s.GetValue()).toBe(100)
    h.expect(cfg:Get("spd")).toBe(100)
    s.SetValue(-5); h.expect(s.GetValue()).toBe(0)
  end)
  h.it("step snaps to nearest", function()
    local s = Slider.new({ Min = 0, Max = 10, Step = 2, Default = 0 })
    s.SetValue(5); h.expect(s.GetValue()).toBe(6)  -- 5 snaps to nearest even -> 6
  end)
  h.it("Title is a 14px label role, Value stays muted, row geometry unchanged (1.2/1.10)", function()
    local s = Slider.new({ Parent = Create("Frame", {}), Text = "Speed", Description = "d", Min = 0, Max = 100, Default = 50 })
    local title = s.Frame:FindFirstChild("Title")
    h.expect(title.TextSize).toBe(R.Theme.Font.label.Size)
    h.expect(title.FontFace.Weight).toBe(R.Theme.Font.label.Weight)
    h.expect(title.Size.Y.Offset).toBe(16)
    h.expect(s.Frame:FindFirstChild("Value").TextSize).toBe(R.Theme.Font.muted.Size)
    h.expect(s.Frame:FindFirstChild("Description").TextSize).toBe(R.Theme.Font.muted.Size)
    h.expect(s.Frame.Size.Y.Offset).toBe(62 + 2 * R.Theme.Spacing.inputY)
    h.expect(s.Frame:FindFirstChild("Track").Position.Y.Offset).toBe(-16)
  end)
end)
h.run()
