local h = require("tests.helper")
local R = h.loadLib()
local Tab, Create = R.Tab, R.Create

local function rig()
  return Create("ScrollingFrame", {}), Create("ScrollingFrame", {})
end

h.describe("tab", function()
  h.it("content is a Frame with UIListLayout + AutomaticSize.Y, hidden by default", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    -- a plain Frame (not CanvasGroup) so focused TextBox carets render
    h.expect(t.Content.ClassName).toBe("Frame")
    h.expect(t.Content.AutomaticSize.Name).toBe("Y")
    h.expect(t.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
    h.expect(t.Content.Visible).toBe(false)
  end)
  h.it("Select shows + slides the content into place and highlights the button", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    h.expect(t.Content.Visible).toBe(true)
    h.expect(t:IsSelected()).toBe(true)
    h.expect(t.Content.Position.Y.Offset).toBe(0)  -- carousel slide settled at 0
    h.expect(t.Button.BackgroundTransparency).toBe(0)
  end)
  h.it("Deselect slides the outgoing page out then hides + resets it", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    t:Deselect()
    h.expect(t:IsSelected()).toBe(false)
    h.expect(t.Content.Visible).toBe(false)
    h.expect(t.Content.Position.Y.Offset).toBe(0)   -- reset after the exit tween, not left mid-slide
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("hovering an unselected tab tints the button, leaving clears it", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t.Button.MouseEnter:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(0.92)
    t.Button.MouseLeave:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("MountRow parents to content with incrementing order (no Position set)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local r = Create("Frame", {})
    local o = t.MountRow(r)
    h.expect(r.Parent).toBe(t.Content)
    h.expect(r.LayoutOrder).toBe(o)
  end)
  h.it("AddAccordion mounts an accordion into content", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local acc = t:AddAccordion({ Title = "Adv" })
    h.expect(acc.Container.Parent).toBe(t.Content)
  end)
  h.it("no longer creates a per-tab Active indicator (the window owns a shared one now)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    h.expect(t.Button:FindFirstChild("Active")).toBe(nil)
    h.expect(t.Button:FindFirstChild("Icon").Position.X.Offset).toBe(4)  -- icon layout unchanged
  end)
end)


-- Visual polish (plan 1.2 / 1.8): real font role, one filmstrip curve, symmetric select, hover text tint.
h.describe("tab polish", function()
  local Enum, mock, theme = h.roblox.Enum, h.mock, R.Theme

  h.it("Label uses the theme label role (Medium 14) and truncates at the end", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local label = t.Button:FindFirstChild("Label")
    h.expect(label.Font).toBe(Enum.Font.BuilderSans)
    h.expect(label.TextSize).toBe(theme.Font.label.Size)
    h.expect(label.FontFace.Weight).toBe(theme.Font.label.Weight)
    h.expect(label.TextTruncate).toBe(Enum.TextTruncate.AtEnd)
  end)
  h.it("Select and Deselect slide the content on the same Quint curve (one filmstrip)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    mock.resetTweens()
    t:Select()
    local inTw = mock.tweensFor(t.Content)
    h.expect(#inTw).toBe(1)
    h.expect(inTw[1].Info.EasingStyle).toBe(Enum.EasingStyle.Quint)
    mock.resetTweens()
    t:Deselect()
    local outTw = mock.tweensFor(t.Content)
    h.expect(#outTw).toBe(1)
    h.expect(outTw[1].Info.EasingStyle).toBe(Enum.EasingStyle.Quint)
    h.expect(outTw[1].Info.Time).toBe(theme.Motion.slow)
  end)
  h.it("Select tweens the fill 1->0, Deselect 0->1 over Motion.fast; label + icon tint through tweens", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    local label, icon = t.Button:FindFirstChild("Label"), t.Button:FindFirstChild("Icon")
    mock.resetTweens()
    t:Select()
    local sel = mock.tweensFor(t.Button)
    h.expect(#sel).toBe(1)                                  -- the BackgroundColor3 no-op tween is gone
    h.expect(sel[1].Goal.BackgroundColor3).toBeNil()
    h.expect(sel[1].Goal.BackgroundTransparency).toBe(0)
    h.expect(sel[1].Info.Time).toBe(theme.Motion.fast)
    h.expect(mock.tweensFor(label)[1].Goal.TextColor3).toBe(theme.Colors.foreground)
    h.expect(mock.tweensFor(icon)[1].Goal.ImageColor3).toBe(theme.Colors.foreground)
    mock.resetTweens()
    t:Deselect()
    local out = mock.tweensFor(t.Button)
    h.expect(#out).toBe(1)
    h.expect(out[1].Goal.BackgroundTransparency).toBe(1)
    h.expect(out[1].Info.Time).toBe(theme.Motion.fast)
    h.expect(mock.tweensFor(label)[1].Goal.TextColor3).toBe(theme.Colors.mutedForeground)
    h.expect(mock.tweensFor(icon)[1].Goal.ImageColor3).toBe(theme.Colors.mutedForeground)
  end)
  h.it("hovering an unselected tab lifts label + icon to foreground; leaving restores muted", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    local label, icon = t.Button:FindFirstChild("Label"), t.Button:FindFirstChild("Icon")
    t.Button.MouseEnter:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.foreground)
    h.expect(icon.ImageColor3).toBe(theme.Colors.foreground)
    h.expect(t.Button.BackgroundTransparency).toBe(theme.Opacity.tabHover)
    h.expect(t.Button:FindFirstChild("Hover")).toBe(nil)   -- text kind: no wash Frame under the button
    t.Button.MouseLeave:Fire()
    h.expect(label.TextColor3).toBe(theme.Colors.mutedForeground)
    h.expect(icon.ImageColor3).toBe(theme.Colors.mutedForeground)
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("a selected tab keeps its foreground text and solid fill across hover enter/leave", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    local label, icon = t.Button:FindFirstChild("Label"), t.Button:FindFirstChild("Icon")
    t:Select()
    t.Button.MouseEnter:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(0)
    t.Button.MouseLeave:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(0)
    h.expect(label.TextColor3).toBe(theme.Colors.foreground)
    h.expect(icon.ImageColor3).toBe(theme.Colors.foreground)
  end)
  h.it("hover wash reads Opacity.tabHover from the tab's own theme", function()
    local side, body = rig()
    local custom = R.Theme.new({ Opacity = { tabHover = 0.8 } })
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Theme = custom })
    t.Button.MouseEnter:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(0.8)
  end)
  h.it("touch release clears the wash (no MouseLeave ever comes on touch)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local prev = mock.lastInputType
    mock.lastInputType = Enum.UserInputType.Touch
    t.Button.MouseEnter:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(theme.Opacity.tabHover)
    t.Button.MouseButton1Up:Fire()
    mock.lastInputType = prev
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("skips hover wiring entirely when the device has no pointer", function()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.MouseEnabled = false
    local ok, err = pcall(function()
      local side, body = rig()
      local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
      t.Button.MouseEnter:Fire()
      h.expect(t.Button.BackgroundTransparency).toBe(1)
      h.expect(t.Button:FindFirstChild("Label").TextColor3).toBe(theme.Colors.mutedForeground)
    end)
    uis.MouseEnabled = true
    if not ok then error(err, 0) end
  end)
  h.it("themer closure re-derives fill, label and icon from the selected state by token name", function()
    local side, body = rig()
    local custom, themer = R.Theme.new(), R.Themer.new()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home",
      Theme = custom, AccentThemer = themer })
    local label, icon = t.Button:FindFirstChild("Label"), t.Button:FindFirstChild("Icon")
    R.Theme.applyMode(custom, "light")
    themer.reskin("mode")
    h.expect(t.Button.BackgroundColor3).toBe(R.Theme.PALETTES.light.surface) -- unselected too: the wash shows this fill
    h.expect(label.TextColor3).toBe(R.Theme.PALETTES.light.mutedForeground)
    h.expect(icon.ImageColor3).toBe(R.Theme.PALETTES.light.mutedForeground)
    t:Select()
    R.Theme.applyMode(custom, "dark")
    themer.reskin("mode")
    h.expect(t.Button.BackgroundColor3).toBe(R.Theme.PALETTES.dark.surface)
    h.expect(label.TextColor3).toBe(R.Theme.PALETTES.dark.foreground)
    h.expect(icon.ImageColor3).toBe(R.Theme.PALETTES.dark.foreground)
  end)
  h.it("themer closure keeps a hovered unselected tab lifted, and leave still restores muted", function()
    local side, body = rig()
    local custom, themer = R.Theme.new(), R.Themer.new()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Theme = custom, AccentThemer = themer })
    local label = t.Button:FindFirstChild("Label")
    t.Button.MouseEnter:Fire()
    R.Theme.applyMode(custom, "light")
    themer.reskin("mode")
    h.expect(label.TextColor3).toBe(R.Theme.PALETTES.light.foreground)
    t.Button.MouseLeave:Fire()
    h.expect(label.TextColor3).toBe(R.Theme.PALETTES.light.mutedForeground)
  end)
  h.it("reduced motion: Select/Deselect and hover land their goals with zero tweens", function()
    h.withReducedMotion(R, function()
      local side, body = rig()
      local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
      mock.resetTweens()
      t:Select()
      h.expect(t.Button.BackgroundTransparency).toBe(0)
      h.expect(t.Content.Position.Y.Offset).toBe(0)
      t:Deselect()
      h.expect(t.Button.BackgroundTransparency).toBe(1)
      h.expect(t.Content.Visible).toBe(false)
      t.Button.MouseEnter:Fire()
      h.expect(t.Button.BackgroundTransparency).toBe(theme.Opacity.tabHover)
      h.expect(t.Button:FindFirstChild("Label").TextColor3).toBe(theme.Colors.foreground)
      h.expect(mock.tweenCount()).toBe(0)
    end)
  end)
end)

h.run()
