local h = require("tests.helper")
local R = h.loadLib()
local TextBox, Create, Config = R.TextBox, R.Create, R.Config

h.describe("textbox", function()
  h.it("the input box clips so a long value does not overflow the field", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "URL", Default = string.rep("x", 200) })
    h.expect(tb.Frame:FindFirstChild("Box").ClipsDescendants).toBe(true)
  end)
  h.it("SetText/GetText round-trip and persist", function()
    local cfg = Config.new({ FileName = "TB", AutoSave = false })
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Player", Flag = "name", Config = cfg })
    h.expect(tb.GetText()).toBe("Player")
    tb.SetText("Neo")
    h.expect(tb.GetText()).toBe("Neo")
    h.expect(cfg:Get("name")).toBe("Neo")
  end)
  h.it("copyable variant exposes a copy button", function()
    local tb = TextBox.new({ Text = "Key", Default = "abc", Copyable = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy") ~= nil).toBeTruthy()
  end)
  h.it("places the box on the right half when Text is set, full-width without", function()
    local a = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local b = TextBox.new({ Parent = Create("Frame", {}) })
    h.expect(b.Frame:FindFirstChild("Box").Size.X.Scale).toBe(1)
  end)
  h.it("renders a Description when given", function()
    local c = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Description = "Your display name" })
    local d = c.Frame:FindFirstChild("Description")
    h.expect(d ~= nil).toBeTruthy(); h.expect(d.Text).toBe("Your display name")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(tb.Frame.BackgroundTransparency).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
  h.it("box is a horizontal flex row and the input flex-fills", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    local box = tb.Frame:FindFirstChild("Box")
    local layout = box:FindFirstChildOfClass("UIListLayout")
    h.expect(layout ~= nil).toBeTruthy()
    h.expect(layout.FillDirection).toBe(h.roblox.Enum.FillDirection.Horizontal)
    local input = box:FindFirstChild("Input")
    h.expect(input:FindFirstChildOfClass("UIFlexItem").FlexMode).toBe(h.roblox.Enum.UIFlexMode.Fill)
  end)
  h.it("FullWidth stacks the label on top and makes the box full width", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Website", FullWidth = true })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box.Size.X.Scale).toBe(1)
    h.expect(box.Position.X.Scale).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Title") ~= nil).toBeTruthy()
  end)
  h.it("renders leading/trailing decorative icons", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Find", LeadingIcon = "search", TrailingIcon = "check" })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("LeadingIcon") ~= nil).toBeTruthy()
    h.expect(box:FindFirstChild("LeadingIcon").LayoutOrder).toBe(1)
    h.expect(box:FindFirstChild("TrailingIcon") ~= nil).toBeTruthy()
  end)
  h.it("input sits between leading and trailing addons in LayoutOrder", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "URL",
      LeadingIcon = "search", Prefix = "https://", Suffix = ".com", Buttons = { { Text = "Go" } } })
    local box = tb.Frame:FindFirstChild("Box")
    local input = box:FindFirstChild("Input")
    h.expect(box:FindFirstChild("LeadingIcon").LayoutOrder < input.LayoutOrder).toBeTruthy()
    h.expect(box:FindFirstChild("Prefix").LayoutOrder < input.LayoutOrder).toBeTruthy()
    h.expect(input.LayoutOrder < box:FindFirstChild("Suffix").LayoutOrder).toBeTruthy()
    h.expect(input.LayoutOrder < box:FindFirstChild("Button1").LayoutOrder).toBeTruthy()
  end)
  h.it("renders muted prefix and suffix text", function()
    local R = h.loadLib()
    local tb = R.TextBox.new({ Parent = R.Create("Frame", {}), Text = "URL", Prefix = "https://", Suffix = ".com" })
    local box = tb.Frame:FindFirstChild("Box")
    local pre = box:FindFirstChild("Prefix")
    h.expect(pre ~= nil).toBeTruthy()
    h.expect(pre.Text).toBe("https://")
    h.expect(pre.TextColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
    h.expect(box:FindFirstChild("Suffix").Text).toBe(".com")
  end)
  h.it("renders inline buttons that receive current text", function()
    local got
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", Default = "abc",
      Buttons = { { Text = "Send", Variant = "default", Callback = function(text) got = text end } } })
    local box = tb.Frame:FindFirstChild("Box")
    local btn = box:FindFirstChild("Button1")
    h.expect(btn ~= nil).toBeTruthy()
    h.expect(btn.Text).toBe("Send")
    btn.MouseButton1Click:Fire()
    h.expect(got).toBe("abc")
  end)
  h.it("icon buttons render and fire their callback", function()
    local hit = false
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "K",
      Buttons = { { Icon = "copy", Callback = function() hit = true end } } })
    local btn = tb.Frame:FindFirstChild("Box"):FindFirstChild("Button1")
    h.expect(btn.ClassName).toBe("ImageButton")
    btn.MouseButton1Click:Fire()
    h.expect(hit).toBe(true)
  end)
  h.it("Clearable exposes a Clear button that empties the value", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Neo", Clearable = true })
    local clear = tb.Frame:FindFirstChild("Box"):FindFirstChild("Clear")
    h.expect(clear ~= nil).toBeTruthy()
    clear.MouseButton1Click:Fire()
    h.expect(tb.GetText()).toBe("")
  end)
  h.it("focus ring switches the stroke to the ring color, restores border on blur", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Name" })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Focused:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.ring.R8)
    input.FocusLost:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("Disabled makes the input non-editable", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Disabled = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Input").TextEditable).toBe(false)
  end)
  h.it("SetInvalid shows a destructive message and stroke; SetValid clears it", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Key", FullWidth = true })
    tb.SetInvalid("Required")
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    local msg = tb.Frame:FindFirstChild("Error")
    h.expect(msg ~= nil).toBeTruthy()
    h.expect(msg.Text).toBe("Required")
    h.expect(msg.Visible).toBe(true)
    tb.SetValid()
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(false)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("Validate runs on commit and marks invalid", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", FullWidth = true,
      Validate = function(t) return #t > 0, "Required" end })
    tb.SetText("")
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(true)
    tb.SetText("ok")
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(false)
  end)
  h.it("Loading shows a spinner; SetLoading(false) hides it", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("Spinner") ~= nil).toBeTruthy()
    h.expect(box:FindFirstChild("Spinner").Visible).toBe(true)
    tb.SetLoading(false)
    h.expect(box:FindFirstChild("Spinner").Visible).toBe(false)
  end)
  h.it("Password masks the display but GetText returns the real value", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    local function typeVis(vis) input.Text = vis; input:GetPropertyChangedSignal("Text"):Fire() end
    typeVis("s")
    h.expect(input.Text).toBe("*")
    h.expect(tb.GetText()).toBe("s")
    typeVis("*e")
    h.expect(input.Text).toBe("**")
    h.expect(tb.GetText()).toBe("se")
    typeVis("**c")
    h.expect(tb.GetText()).toBe("sec")
  end)
  h.it("masked typing keeps the caret at the end (no flicker reset)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Text = "ab"; input:GetPropertyChangedSignal("Text"):Fire()
    h.expect(input.Text).toBe("**")
    h.expect(input.CursorPosition).toBe(3)
  end)
  h.it("unmasked typing does not rewrite Input.Text (caret stays put)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.CursorPosition = 3
    input.Text = "abc"; input:GetPropertyChangedSignal("Text"):Fire()
    -- render() must not touch Text (it already equals real), so the caret is untouched
    h.expect(input.Text).toBe("abc")
    h.expect(input.CursorPosition).toBe(3)
  end)
  h.it("Password eye toggle reveals and re-masks", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true, Default = "abc" })
    local box = tb.Frame:FindFirstChild("Box")
    local input = box:FindFirstChild("Input")
    h.expect(input.Text).toBe("***")
    box:FindFirstChild("Eye").MouseButton1Click:Fire()
    h.expect(input.Text).toBe("abc")
    box:FindFirstChild("Eye").MouseButton1Click:Fire()
    h.expect(input.Text).toBe("***")
  end)
  -- ---- visual-polish phase 1 (1.2 font roles, 1.7 focus ring, 1.9 spin) ----
  h.it("Title/Description/Input/affixes carry the label/muted/body font roles", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "URL", Description = "where",
      Prefix = "https://", Buttons = { { Text = "Go" } } })
    local box = tb.Frame:FindFirstChild("Box")
    local ti, de = tb.Frame:FindFirstChild("Title"), tb.Frame:FindFirstChild("Description")
    h.expect(ti.TextSize).toBe(R2.Theme.Font.label.Size)
    h.expect(ti.FontFace.Weight).toBe(R2.Theme.Font.label.Weight)
    h.expect(de.TextSize).toBe(R2.Theme.Font.muted.Size)
    local input = box:FindFirstChild("Input")
    h.expect(input.TextSize).toBe(R2.Theme.Font.body.Size)
    h.expect(input.FontFace.Weight).toBe(R2.Theme.Font.body.Weight)
    h.expect(input.Font).toBe(h.roblox.Enum.Font.BuilderSans)
    h.expect(box:FindFirstChild("Prefix").TextSize).toBe(R2.Theme.Font.body.Size)
    h.expect(box:FindFirstChild("Button1").TextSize).toBe(R2.Theme.Font.muted.Size)
    tb.SetInvalid("Required")
    h.expect(tb.Frame:FindFirstChild("Error").TextSize).toBe(R2.Theme.Font.muted.Size)
  end)
  h.it("focus ring thickens the stroke to Stroke.focusThickness and restores 1 on blur", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Name" })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(stroke.Thickness).toBe(1)
    input.Focused:Fire()
    h.expect(stroke.Thickness).toBe(R2.Theme.Stroke.focusThickness)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.ring.R8)
    input.FocusLost:Fire()
    h.expect(stroke.Thickness).toBe(1)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("invalid outranks the ring colour while the thickness still follows focus", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Key", FullWidth = true })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    tb.SetInvalid("Required")
    input.Focused:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    h.expect(stroke.Thickness).toBe(R2.Theme.Stroke.focusThickness)
    input.FocusLost:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    h.expect(stroke.Thickness).toBe(1)
    tb.SetValid()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("spinner runs an endless Animate.spin loop that SetLoading(false) cancels", function()
    h.mock.resetTweens()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local spinner = tb.Frame:FindFirstChild("Box"):FindFirstChild("Spinner")
    local tw = h.mock.tweensFor(spinner)[1]
    h.expect(tw ~= nil).toBeTruthy()
    h.expect(tw.Info.RepeatCount).toBe(-1)
    h.expect(tw.cancelled).toBe(false)
    tb.SetLoading(false)
    h.expect(tw.cancelled).toBe(true)
    h.expect(spinner.Rotation).toBe(0)
  end)
  h.it("Destroy cancels a running spin loop", function()
    h.mock.resetTweens()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local tw = h.mock.tweensFor(tb.Frame:FindFirstChild("Box"):FindFirstChild("Spinner"))[1]
    tb.Destroy()
    h.expect(tw.cancelled).toBe(true)
  end)
  h.it("reduced motion: no spin tween is created, the glyph rests at 0 and the ring snaps", function()
    h.withReducedMotion(R, function()
      h.mock.resetTweens()
      local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
      local box = tb.Frame:FindFirstChild("Box")
      local spinner, stroke = box:FindFirstChild("Spinner"), box:FindFirstChildOfClass("UIStroke")
      h.expect(#h.mock.tweensFor(spinner)).toBe(0)
      h.expect(spinner.Rotation).toBe(0)
      box:FindFirstChild("Input").Focused:Fire()
      h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
      h.expect(#h.mock.tweensFor(stroke)).toBe(0)
      tb.SetLoading(false)
    end)
  end)
end)

h.run()
