local h = require("tests.helper")
local R = h.loadLib()
local TextBox, Create, Config = R.TextBox, R.Create, R.Config

h.describe("textbox", function()
  h.it("the input box clips so a long value does not overflow the field", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "URL", Default = string.rep("x", 200) })
    h.expect(tb.Frame:FindFirstChild("Box").ClipsDescendants).toBe(true)
  end)
  h.it("SetText/GetText round-trip and persist", function()
    local cfg = Config.new({ FileName = "TB", AutoSave = false })
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Player", Flag = "name", Config = cfg })
    h.expect(tb.GetText()).toBe("Player")
    tb.SetText("Neo")
    h.expect(tb.GetText()).toBe("Neo")
    h.expect(cfg:Get("name")).toBe("Neo")
  end)
  h.it("copyable variant exposes a copy button", function()
    local tb = TextBox.new({ Text = "Key", Default = "abc", Copyable = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy") ~= nil).toBeTruthy()
  end)
  h.it("places the box on the right half when Text is set, full-width without", function()
    local a = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local b = TextBox.new({ Parent = Create("Frame", {}) })
    h.expect(b.Frame:FindFirstChild("Box").Size.X.Scale).toBe(1)
  end)
  h.it("renders a Description when given", function()
    local c = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Description = "Your display name" })
    local d = c.Frame:FindFirstChild("Description")
    h.expect(d ~= nil).toBeTruthy(); h.expect(d.Text).toBe("Your display name")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(tb.Frame.BackgroundTransparency).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
  h.it("box is a horizontal flex row and the input flex-fills", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    local box = tb.Frame:FindFirstChild("Box")
    local layout = box:FindFirstChildOfClass("UIListLayout")
    h.expect(layout ~= nil).toBeTruthy()
    h.expect(layout.FillDirection).toBe(h.roblox.Enum.FillDirection.Horizontal)
    local input = box:FindFirstChild("Input")
    h.expect(input:FindFirstChildOfClass("UIFlexItem").FlexMode).toBe(h.roblox.Enum.UIFlexMode.Fill)
  end)
  h.it("FullWidth stacks the label on top and makes the box full width", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Website", FullWidth = true })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box.Size.X.Scale).toBe(1)
    h.expect(box.Position.X.Scale).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Title") ~= nil).toBeTruthy()
  end)
  h.it("renders leading/trailing decorative icons", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Find", LeadingIcon = "search", TrailingIcon = "check" })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("LeadingIcon") ~= nil).toBeTruthy()
    h.expect(box:FindFirstChild("LeadingIcon").LayoutOrder).toBe(1)
    h.expect(box:FindFirstChild("TrailingIcon") ~= nil).toBeTruthy()
  end)
  h.it("input sits between leading and trailing addons in LayoutOrder", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "URL",
      LeadingIcon = "search", Prefix = "https://", Suffix = ".com", Buttons = { { Text = "Go" } } })
    local box = tb.Frame:FindFirstChild("Box")
    local input = box:FindFirstChild("Input")
    h.expect(box:FindFirstChild("LeadingIcon").LayoutOrder < input.LayoutOrder).toBeTruthy()
    h.expect(box:FindFirstChild("Prefix").LayoutOrder < input.LayoutOrder).toBeTruthy()
    h.expect(input.LayoutOrder < box:FindFirstChild("Suffix").LayoutOrder).toBeTruthy()
    h.expect(input.LayoutOrder < box:FindFirstChild("Button1").LayoutOrder).toBeTruthy()
  end)
  h.it("renders muted prefix and suffix text", function()
    local R = h.loadLib()
    local tb = R.TextBox.new({ Parent = R.Create("Frame", {}), Text = "URL", Prefix = "https://", Suffix = ".com" })
    local box = tb.Frame:FindFirstChild("Box")
    local pre = box:FindFirstChild("Prefix")
    h.expect(pre ~= nil).toBeTruthy()
    h.expect(pre.Text).toBe("https://")
    h.expect(pre.TextColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
    h.expect(box:FindFirstChild("Suffix").Text).toBe(".com")
  end)
  h.it("renders inline buttons that receive current text", function()
    local got
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", Default = "abc",
      Buttons = { { Text = "Send", Variant = "default", Callback = function(text) got = text end } } })
    local box = tb.Frame:FindFirstChild("Box")
    local btn = box:FindFirstChild("Button1")
    h.expect(btn ~= nil).toBeTruthy()
    h.expect(btn.Text).toBe("Send")
    btn.MouseButton1Click:Fire()
    h.expect(got).toBe("abc")
  end)
  h.it("icon buttons render and fire their callback", function()
    local hit = false
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "K",
      Buttons = { { Icon = "copy", Callback = function() hit = true end } } })
    local btn = tb.Frame:FindFirstChild("Box"):FindFirstChild("Button1")
    h.expect(btn.ClassName).toBe("ImageButton")
    btn.MouseButton1Click:Fire()
    h.expect(hit).toBe(true)
  end)
  h.it("Clearable exposes a Clear button that empties the value", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Neo", Clearable = true })
    local clear = tb.Frame:FindFirstChild("Box"):FindFirstChild("Clear")
    h.expect(clear ~= nil).toBeTruthy()
    clear.MouseButton1Click:Fire()
    h.expect(tb.GetText()).toBe("")
  end)
  h.it("focus ring switches the stroke to the ring color, restores border on blur", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Name" })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Focused:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.ring.R8)
    input.FocusLost:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("Disabled makes the input non-editable", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Disabled = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Input").TextEditable).toBe(false)
  end)
  h.it("SetInvalid shows a destructive message and stroke; SetValid clears it", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Key", FullWidth = true })
    tb.SetInvalid("Required")
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    local msg = tb.Frame:FindFirstChild("Error")
    h.expect(msg ~= nil).toBeTruthy()
    h.expect(msg.Text).toBe("Required")
    h.expect(msg.Visible).toBe(true)
    tb.SetValid()
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(false)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("Validate runs on commit and marks invalid", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", FullWidth = true,
      Validate = function(t) return #t > 0, "Required" end })
    tb.SetText("")
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(true)
    tb.SetText("ok")
    h.expect(tb.Frame:FindFirstChild("Error").Visible).toBe(false)
  end)
  h.it("Loading shows a spinner; SetLoading(false) hides it", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("Spinner") ~= nil).toBeTruthy()
    h.expect(box:FindFirstChild("Spinner").Visible).toBe(true)
    tb.SetLoading(false)
    h.expect(box:FindFirstChild("Spinner").Visible).toBe(false)
  end)
  h.it("Password masks the display but GetText returns the real value", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    local function typeVis(vis) input.Text = vis; input:GetPropertyChangedSignal("Text"):Fire() end
    typeVis("s")
    h.expect(input.Text).toBe("*")
    h.expect(tb.GetText()).toBe("s")
    typeVis("*e")
    h.expect(input.Text).toBe("**")
    h.expect(tb.GetText()).toBe("se")
    typeVis("**c")
    h.expect(tb.GetText()).toBe("sec")
  end)
  h.it("masked typing keeps the caret at the end (no flicker reset)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.Text = "ab"; input:GetPropertyChangedSignal("Text"):Fire()
    h.expect(input.Text).toBe("**")
    h.expect(input.CursorPosition).toBe(3)
  end)
  h.it("unmasked typing does not rewrite Input.Text (caret stays put)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    input.CursorPosition = 3
    input.Text = "abc"; input:GetPropertyChangedSignal("Text"):Fire()
    -- render() must not touch Text (it already equals real), so the caret is untouched
    h.expect(input.Text).toBe("abc")
    h.expect(input.CursorPosition).toBe(3)
  end)
  h.it("Password eye toggle reveals and re-masks", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true, Default = "abc" })
    local box = tb.Frame:FindFirstChild("Box")
    local input = box:FindFirstChild("Input")
    h.expect(input.Text).toBe("***")
    box:FindFirstChild("Eye").MouseButton1Click:Fire()
    h.expect(input.Text).toBe("abc")
    box:FindFirstChild("Eye").MouseButton1Click:Fire()
    h.expect(input.Text).toBe("***")
  end)
  -- ---- visual-polish phase 1 (1.2 font roles, 1.7 focus ring, 1.9 spin) ----
  h.it("Title/Description/Input/affixes carry the label/muted/body font roles", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "URL", Description = "where",
      Prefix = "https://", Buttons = { { Text = "Go" } } })
    local box = tb.Frame:FindFirstChild("Box")
    local ti, de = tb.Frame:FindFirstChild("Title"), tb.Frame:FindFirstChild("Description")
    h.expect(ti.TextSize).toBe(R2.Theme.Font.label.Size)
    h.expect(ti.FontFace.Weight).toBe(R2.Theme.Font.label.Weight)
    h.expect(de.TextSize).toBe(R2.Theme.Font.muted.Size)
    local input = box:FindFirstChild("Input")
    h.expect(input.TextSize).toBe(R2.Theme.Font.body.Size)
    h.expect(input.FontFace.Weight).toBe(R2.Theme.Font.body.Weight)
    h.expect(input.Font).toBe(h.roblox.Enum.Font.BuilderSans)
    h.expect(box:FindFirstChild("Prefix").TextSize).toBe(R2.Theme.Font.body.Size)
    h.expect(box:FindFirstChild("Button1").TextSize).toBe(R2.Theme.Font.muted.Size)
    tb.SetInvalid("Required")
    h.expect(tb.Frame:FindFirstChild("Error").TextSize).toBe(R2.Theme.Font.muted.Size)
  end)
  h.it("focus ring thickens the stroke to Stroke.focusThickness and restores 1 on blur", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Name" })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    h.expect(stroke.Thickness).toBe(1)
    input.Focused:Fire()
    h.expect(stroke.Thickness).toBe(R2.Theme.Stroke.focusThickness)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.ring.R8)
    input.FocusLost:Fire()
    h.expect(stroke.Thickness).toBe(1)
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("invalid outranks the ring colour while the thickness still follows focus", function()
    local R2 = h.loadLib()
    local tb = R2.TextBox.new({ Parent = R2.Create("Frame", {}), Text = "Key", FullWidth = true })
    local stroke = tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke")
    local input = tb.Frame:FindFirstChild("Box"):FindFirstChild("Input")
    tb.SetInvalid("Required")
    input.Focused:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    h.expect(stroke.Thickness).toBe(R2.Theme.Stroke.focusThickness)
    input.FocusLost:Fire()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.destructive.R8)
    h.expect(stroke.Thickness).toBe(1)
    tb.SetValid()
    h.expect(stroke.Color.R8).toBe(R2.Theme.Colors.border.R8)
  end)
  h.it("spinner runs an endless Animate.spin loop that SetLoading(false) cancels", function()
    h.mock.resetTweens()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local spinner = tb.Frame:FindFirstChild("Box"):FindFirstChild("Spinner")
    local tw = h.mock.tweensFor(spinner)[1]
    h.expect(tw ~= nil).toBeTruthy()
    h.expect(tw.Info.RepeatCount).toBe(-1)
    h.expect(tw.cancelled).toBe(false)
    tb.SetLoading(false)
    h.expect(tw.cancelled).toBe(true)
    h.expect(spinner.Rotation).toBe(0)
  end)
  h.it("Destroy cancels a running spin loop", function()
    h.mock.resetTweens()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
    local tw = h.mock.tweensFor(tb.Frame:FindFirstChild("Box"):FindFirstChild("Spinner"))[1]
    tb.Destroy()
    h.expect(tw.cancelled).toBe(true)
  end)
  h.it("reduced motion: no spin tween is created, the glyph rests at 0 and the ring snaps", function()
    h.withReducedMotion(R, function()
      h.mock.resetTweens()
      local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Sync", Loading = true })
      local box = tb.Frame:FindFirstChild("Box")
      local spinner, stroke = box:FindFirstChild("Spinner"), box:FindFirstChildOfClass("UIStroke")
      h.expect(#h.mock.tweensFor(spinner)).toBe(0)
      h.expect(spinner.Rotation).toBe(0)
      box:FindFirstChild("Input").Focused:Fire()
      h.expect(stroke.Thickness).toBe(R.Theme.Stroke.focusThickness)
      h.expect(#h.mock.tweensFor(stroke)).toBe(0)
      tb.SetLoading(false)
    end)
  end)
  -- ---- visual-polish phase 2 (2.15 shake/fade/copy, 2.7 inline buttons, 2.8 disabled) ----
  h.it("SetInvalid shakes the box on its own X and ends exactly where it started (2.15)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", FullWidth = true })
    local box = tb.Frame:FindFirstChild("Box")
    local x0 = box.Position.X.Offset
    h.mock.resetTweens()
    tb.SetInvalid("Required")
    local sh = R.Theme.Motion.shake
    local tws = h.mock.tweensFor(box)
    h.expect(#tws).toBe(sh.steps + 1)                   -- Motion.shake.steps + the closing return
    h.expect(tws[1].Info.Time).toBe(sh.step)
    h.expect(tws[1].Info.EasingStyle).toBe(h.roblox.Enum.EasingStyle.Sine)
    h.expect(tws[1].Goal.Position.X.Offset).toBe(x0 + sh.amp)
    h.expect(tws[2].Goal.Position.X.Offset).toBe(x0 - sh.amp)
    h.expect(tws[#tws].Goal.Position.X.Offset).toBe(x0)
    h.expect(box.Position.X.Offset).toBe(x0)
    h.expect(box.Position.Y.Offset).toBe(tws[1].Goal.Position.Y.Offset)  -- horizontal only
  end)
  h.it("SetInvalid fades the error in and eases the row; SetValid fades out then hides (2.15)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", FullWidth = true })
    local baseH = tb.Frame.Size.Y.Offset
    tb.SetInvalid("Required")
    local msg = tb.Frame:FindFirstChild("Error")
    h.expect(msg.Visible).toBe(true)                    -- Visible is synchronous, the fade is not
    h.expect(msg.TextTransparency).toBe(0)
    h.expect(tb.Frame.Size.Y.Offset).toBe(baseH + 18)   -- ERROR_H
    local rowTws = h.mock.tweensFor(tb.Frame)
    h.expect(rowTws[#rowTws].Info.Time).toBe(R.Theme.Motion.base)
    local msgTws = h.mock.tweensFor(msg)
    h.expect(msgTws[#msgTws].Goal.TextTransparency).toBe(0)
    tb.SetValid()
    h.expect(msg.TextTransparency).toBe(1)
    h.expect(msg.Visible).toBe(false)                   -- hidden once the fade completes
    h.expect(tb.Frame.Size.Y.Offset).toBe(baseH)
    local out = h.mock.tweensFor(msg)
    h.expect(out[#out].Info.Time).toBe(R.Theme.Motion.fast)
  end)
  h.it("reduced motion: SetInvalid lands its end state with no shake at all", function()
    h.withReducedMotion(R, function()
      local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", FullWidth = true })
      local box = tb.Frame:FindFirstChild("Box")
      local baseH, x0 = tb.Frame.Size.Y.Offset, box.Position.X.Offset
      h.mock.resetTweens()
      tb.SetInvalid("Required")
      h.expect(#h.mock.tweensFor(box)).toBe(0)
      h.expect(box.Position.X.Offset).toBe(x0)
      h.expect(tb.Frame.Size.Y.Offset).toBe(baseH + 18)
      local msg = tb.Frame:FindFirstChild("Error")
      h.expect(msg.Visible).toBe(true)
      h.expect(msg.TextTransparency).toBe(0)
      tb.SetValid()
      h.expect(msg.Visible).toBe(false)
      h.expect(tb.Frame.Size.Y.Offset).toBe(baseH)
    end)
  end)
  h.it("Copy shows a success check for Motion.copyRevert seconds, then reverts (2.15)", function()
    h.withQueuedTimers(function()
      local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", Default = "abc", Copyable = true })
      local copy = tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy")
      copy.MouseButton1Click:Fire()
      h.expect(copy.Image).toBe(R.Icons.get("check").Id)
      h.expect(copy.ImageColor3).toBe(R.Theme.Colors.success)
      h.expect(h.mock.timerCount()).toBe(1)             -- one parked revert, not a busy loop
      h.mock.advance(R.Theme.Motion.copyRevert)
      h.expect(copy.Image).toBe(R.Icons.get("copy").Id)
      h.expect(copy.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.accent])
    end)
  end)
  h.it("a second Copy click owns the revert window (no early flip back)", function()
    h.withQueuedTimers(function()
      local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", Default = "abc", Copyable = true })
      local copy = tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy")
      copy.MouseButton1Click:Fire()
      h.mock.advance(R.Theme.Motion.copyRevert / 2)
      copy.MouseButton1Click:Fire()                     -- restarts the window
      h.mock.advance(R.Theme.Motion.copyRevert / 2 + 0.01)
      h.expect(copy.Image).toBe(R.Icons.get("check").Id)  -- the first timer must not revert it
      h.mock.advance(R.Theme.Motion.copyRevert)
      h.expect(copy.Image).toBe(R.Icons.get("copy").Id)
    end)
  end)
  h.it("Clear fades its glyph and only hides once faded; typing fades it back in (2.15)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Neo", Clearable = true })
    local box = tb.Frame:FindFirstChild("Box")
    local clear, input = box:FindFirstChild("Clear"), box:FindFirstChild("Input")
    h.expect(clear.Visible).toBe(true)
    h.expect(clear.ImageTransparency).toBe(0)
    h.expect(#h.mock.tweensFor(clear)).toBe(0)          -- the first sync lands instantly
    clear.MouseButton1Click:Fire()
    input:GetPropertyChangedSignal("Text"):Fire()       -- the mock never auto-fires property signals
    h.expect(tb.GetText()).toBe("")
    h.expect(clear.ImageTransparency).toBe(1)
    h.expect(clear.Visible).toBe(false)
    local tws = h.mock.tweensFor(clear)
    h.expect(tws[#tws].Info.Time).toBe(R.Theme.Motion.fast)
    tb.SetText("x")
    input:GetPropertyChangedSignal("Text"):Fire()
    h.expect(clear.Visible).toBe(true)
    h.expect(clear.ImageTransparency).toBe(0)
  end)
  h.it("the eye glyph swaps and pops on toggle (2.15)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Pass", Password = true, Default = "abc" })
    local eye = tb.Frame:FindFirstChild("Box"):FindFirstChild("Eye")
    eye.MouseButton1Click:Fire()
    h.expect(eye.ImageRectOffset.X).toBe(R.Icons.get("eye-off").ImageRectOffset.X)
    local us = eye:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(us.Scale).toBe(1)                          -- pops back to rest, never parks at popFrom
    local tws = h.mock.tweensFor(us)
    h.expect(tws[#tws].Goal.Scale).toBe(1)
    h.expect(tws[#tws].Info.Time).toBe(R.Theme.Motion.fast)
  end)
  h.it("inline buttons lift their tint on hover and dip their scale on press (2.7)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Neo", Clearable = true })
    local clear = tb.Frame:FindFirstChild("Box"):FindFirstChild("Clear")
    h.expect(clear.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.structural])
    clear.MouseEnter:Fire()
    h.expect(clear.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.structuralActive])
    clear.MouseButton1Down:Fire()
    h.expect(clear:FindFirstChildOfClass("UIScale").Scale).toBe(R.Theme.Motion.pressScale)
    clear.MouseButton1Up:Fire()
    h.expect(clear:FindFirstChildOfClass("UIScale").Scale).toBe(1)
    clear.MouseLeave:Fire()
    h.expect(clear.ImageColor3).toBe(R.Theme.Colors[R.Theme.Icon.structural])
  end)
  h.it("an inline text button dips its own fill on hover (no wash over its label) (2.7)", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "URL", Buttons = { { Text = "Go" } } })
    local btn = tb.Frame:FindFirstChild("Box"):FindFirstChild("Button1")
    h.expect(btn:FindFirstChild("Hover")).toBeNil()     -- a wash child would cover the button Text
    h.expect(btn.BackgroundTransparency).toBe(0)
    btn.MouseEnter:Fire()
    h.expect(btn.BackgroundTransparency).toBe(R.Theme.Opacity.hoverFill)
    btn.MouseLeave:Fire()
    h.expect(btn.BackgroundTransparency).toBe(0)
  end)
  h.it("SetEnabled(false) dims box + glyphs, guards callbacks, and still applies SetText (2.8)", function()
    local hits = 0
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Key", Default = "abc", Clearable = true,
      Buttons = { { Icon = "copy", Callback = function() hits = hits + 1 end } } })
    local box = tb.Frame:FindFirstChild("Box")
    local btn, input = box:FindFirstChild("Button1"), box:FindFirstChild("Input")
    tb.SetEnabled(false)
    h.expect(box.BackgroundTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(btn.ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(box:FindFirstChild("Clear").ImageTransparency).toBe(R.Theme.Opacity.disabled)
    h.expect(input.TextEditable).toBe(false)
    btn.MouseButton1Click:Fire()
    h.expect(hits).toBe(0)
    tb.SetText("zzz")                                   -- config/apply path still applies (2.8a)
    h.expect(tb.GetText()).toBe("zzz")
    tb.SetEnabled(true)
    h.expect(box.BackgroundTransparency).toBe(0)
    h.expect(btn.ImageTransparency).toBe(0)
    h.expect(input.TextEditable).toBe(true)
    btn.MouseButton1Click:Fire()
    h.expect(hits).toBe(1)
  end)
  h.it("SetEnabled and the host's SetLocked are independent flags (2.8c)", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "W", Parent = screen })
    local tb = w:AddTab({ Name = "T" }):AddTextBox({ Text = "Name" })
    tb.SetLocked(true); tb.SetEnabled(false)
    local scrim = tb.Frame:FindFirstChild("LockScrim")
    h.expect(scrim.Visible).toBe(true)
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundTransparency).toBe(R.Theme.Opacity.disabled)
    tb.SetEnabled(true)
    h.expect(scrim.Visible).toBe(true)                  -- releasing one never releases the other
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundTransparency).toBe(0)
    tb.SetLocked(false)
    h.expect(scrim.Visible).toBe(false)
  end)
end)

h.run()
