local h = require("tests.helper")
local R = h.loadLib(); local Themer = R.Themer
h.describe("themer", function()
  h.it("register/reskin fires live closures; unregister removes them; setAccent triggers reskin", function()
    local t = Themer.new(); local n = 0
    local off = t.register(function() n = n + 1 end)
    t.reskin(); h.expect(n).toBe(1)
    t.setAccent(); h.expect(n).toBe(2)
    off(); t.reskin(); h.expect(n).toBe(2)
  end)
  h.it("ships named accent presets", function()
    h.expect(Themer.accent("Indigo") ~= nil).toBeTruthy()
    h.expect(Themer.accent("Nope")).toBe(nil)
  end)
  h.it("Window:SetAccent recolors a default button live", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local btn = tab:AddButton({ Text = "Go" }) -- default variant
    w:SetAccent("Indigo")
    local ind = Themer.accent("Indigo")
    h.expect(btn.Frame:FindFirstChild("Surface").BackgroundColor3).toBe(ind.Primary)
  end)
  h.it("recolors toggle (on), slider fill, progressbar, and active tab indicator", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local tog = tab:AddToggle({ Text = "t", Default = true })
    local sl = tab:AddSlider({ Text = "s", Min = 0, Max = 10, Default = 5 })
    local pb = tab:AddProgressBar({ Default = 0.5 })
    w:SetAccent("Emerald")
    local em = Themer.accent("Emerald")
    h.expect(tog.Frame:FindFirstChild("Track").BackgroundColor3).toBe(em.Primary)
    h.expect(sl.Frame:FindFirstChild("Track"):FindFirstChild("Fill").BackgroundColor3).toBe(em.Primary)
    h.expect(pb.Frame:FindFirstChild("Track"):FindFirstChild("Fill").BackgroundColor3).toBe(em.Primary)
    local body = w.Main:FindFirstChild("Body")
    h.expect(body:FindFirstChild("ActiveIndicator").BackgroundColor3).toBe(em.Primary)
  end)
  h.it("Adaptive accent follows the mode; presets persist across mode", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" }); local btn = tab:AddButton({ Text = "Go" })
    w:SetAccent("Adaptive")
    h.expect(btn.Frame:FindFirstChild("Surface").BackgroundColor3).toBe(R.Theme.PALETTES.dark.primary)
    w:SetMode("light")
    h.expect(btn.Frame:FindFirstChild("Surface").BackgroundColor3).toBe(R.Theme.PALETTES.light.primary)
    w:SetAccent("Indigo"); w:SetMode("dark")
    h.expect(btn.Frame:FindFirstChild("Surface").BackgroundColor3).toBe(R.Themer.accent("Indigo").Primary)
  end)
  h.it("SetMode recolors the window shell and preserves the accent", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    w:SetAccent(h.roblox.Color3.fromRGB(10, 20, 30))
    w:SetMode("light")
    h.expect(w:GetMode()).toBe("light")
    h.expect(w.Main.BackgroundColor3).toBe(R.Theme.PALETTES.light.background)
    local title = w.Main:FindFirstChild("TitleBar"):FindFirstChild("Title")
    h.expect(title.TextColor3).toBe(R.Theme.PALETTES.light.foreground)
  end)
end)
h.describe("themer reskin reason", function()
  h.it("reskin(reason) forwards the reason to every registered closure", function()
    local t = Themer.new(); local seen = {}
    t.register(function(reason) seen[#seen + 1] = reason end)
    t.register(function(reason) seen[#seen + 1] = reason end)
    t.reskin("mode")
    h.expect(seen).toHaveLength(2)
    h.expect(seen[1]).toBe("mode"); h.expect(seen[2]).toBe("mode")
  end)
  h.it("setAccent reskins with reason 'accent'", function()
    local t = Themer.new(); local got = "unset"
    t.register(function(reason) got = reason end)
    t.setAccent()
    h.expect(got).toBe("accent")
  end)
  h.it("reskin() without a reason passes nil so legacy callers keep working", function()
    local t = Themer.new(); local n, got = 0, "unset"
    t.register(function(reason) n = n + 1; got = reason end)
    t.reskin()
    h.expect(n).toBe(1); h.expect(got).toBe(nil)
  end)
  h.it("a throwing closure is isolated and does not stop the others", function()
    local t = Themer.new(); local ran = false
    t.register(function() error("boom") end)
    t.register(function() ran = true end)
    t.reskin("accent")
    h.expect(ran).toBe(true)
  end)
end)
h.run()
